// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Cbn20170912.Models
{
    public class ListTransitRouterRouteEntriesResponseBody : TeaModel {
        /// <summary>
        /// <para>The number of entries per page.</para>
        /// 
        /// <b>Example:</b>
        /// <para>20</para>
        /// </summary>
        [NameInMap("MaxResults")]
        [Validation(Required=false)]
        public int? MaxResults { get; set; }

        /// <summary>
        /// <para>A pagination token. It can be used in the next request to retrieve a new page of results. Valid values:</para>
        /// <list type="bullet">
        /// <item><description>If <b>NextToken</b> is empty, no next page exists.</description></item>
        /// <item><description>If a value is returned for <b>NextToken</b>, the value is the token that determines the start point of the next query.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>fce19****</para>
        /// </summary>
        [NameInMap("NextToken")]
        [Validation(Required=false)]
        public string NextToken { get; set; }

        /// <summary>
        /// <para>The request ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>C3835E5E-1504-4344-B1BB-98A4110F1079</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>The total number of entries returned.</para>
        /// 
        /// <b>Example:</b>
        /// <para>6</para>
        /// </summary>
        [NameInMap("TotalCount")]
        [Validation(Required=false)]
        public int? TotalCount { get; set; }

        /// <summary>
        /// <para>A list of route entries.</para>
        /// </summary>
        [NameInMap("TransitRouterRouteEntries")]
        [Validation(Required=false)]
        public List<ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries> TransitRouterRouteEntries { get; set; }
        public class ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries : TeaModel {
            /// <summary>
            /// <para>The time when the route entry was created.</para>
            /// <para>The time follows the ISO8601 standard in the YYYY-MM-DDThh:mmZ format. The time is displayed in UTC.</para>
            /// <remarks>
            /// <para> This parameter is returned only for static routes.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>2021-06-15T07:01Z</para>
            /// </summary>
            [NameInMap("CreateTime")]
            [Validation(Required=false)]
            public string CreateTime { get; set; }

            /// <summary>
            /// <para>Indicates whether the route can be managed. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>true</b>: The route can be managed. You can delete the route.</description></item>
            /// <item><description><b>false</b>: The route cannot be managed because it is automatically generated by the system.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>false</para>
            /// </summary>
            [NameInMap("OperationalMode")]
            [Validation(Required=false)]
            public bool? OperationalMode { get; set; }

            /// <summary>
            /// <para>The route attributes.</para>
            /// </summary>
            [NameInMap("PathAttributes")]
            [Validation(Required=false)]
            public ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes PathAttributes { get; set; }
            public class ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes : TeaModel {
                /// <summary>
                /// <para>The route AS path.</para>
                /// </summary>
                [NameInMap("AsPaths")]
                [Validation(Required=false)]
                public List<string> AsPaths { get; set; }

                /// <summary>
                /// <para>The route community.</para>
                /// </summary>
                [NameInMap("Communities")]
                [Validation(Required=false)]
                public List<string> Communities { get; set; }

                /// <summary>
                /// <para>The source instance ID.</para>
                /// 
                /// <b>Example:</b>
                /// <para>vbr-m5ent6du8deaq5*****</para>
                /// </summary>
                [NameInMap("OriginInstanceId")]
                [Validation(Required=false)]
                public string OriginInstanceId { get; set; }

                /// <summary>
                /// <para>The source instance type. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><b>VPC</b></description></item>
                /// <item><description><b>VBR</b></description></item>
                /// <item><description><b>TR</b></description></item>
                /// <item><description><b>VPN</b></description></item>
                /// <item><description><b>CCN</b></description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>VBR</para>
                /// </summary>
                [NameInMap("OriginInstanceType")]
                [Validation(Required=false)]
                public string OriginInstanceType { get; set; }

                /// <summary>
                /// <para>The route type. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><b>System</b></description></item>
                /// <item><description><b>Custom</b></description></item>
                /// <item><description><b>static</b></description></item>
                /// <item><description><b>BGP</b></description></item>
                /// <item><description><b>BlackHole</b></description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>BGP</para>
                /// </summary>
                [NameInMap("OriginRouteType")]
                [Validation(Required=false)]
                public string OriginRouteType { get; set; }

                /// <summary>
                /// <para>The route priority.</para>
                /// <para>A smaller value indicates a higher priority.</para>
                /// 
                /// <b>Example:</b>
                /// <para>50</para>
                /// </summary>
                [NameInMap("Preference")]
                [Validation(Required=false)]
                public int? Preference { get; set; }

            }

            /// <summary>
            /// <para>The prefix list ID.</para>
            /// 
            /// <b>Example:</b>
            /// <para>pl-k1ainl66z3527773d****</para>
            /// </summary>
            [NameInMap("PrefixListId")]
            [Validation(Required=false)]
            public string PrefixListId { get; set; }

            /// <summary>
            /// <para>The route tag.</para>
            /// <para>Only <b>PermitVbr</b> may be returned, which indicates that the route is advertised only to the route tables of the virtual border routers (VBRs) that are connected to the transit router.</para>
            /// <remarks>
            /// <para> This parameter is returned only for routes whose CIDR blocks are automatically generated by the system.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>PermitVbr</para>
            /// </summary>
            [NameInMap("Tag")]
            [Validation(Required=false)]
            public string Tag { get; set; }

            /// <summary>
            /// <para>The route description.</para>
            /// <remarks>
            /// <para> This parameter is returned only for static routes.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>CidrRoute</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryDescription")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryDescription { get; set; }

            /// <summary>
            /// <para>The destination CIDR block of the route.</para>
            /// 
            /// <b>Example:</b>
            /// <para>192.168.0.0/24</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryDestinationCidrBlock")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryDestinationCidrBlock { get; set; }

            /// <summary>
            /// <para>The route ID.</para>
            /// <remarks>
            /// <para> This parameter is returned only for static routes.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>rte-oklkgwmj97z6dn****</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryId")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryId { get; set; }

            /// <summary>
            /// <para>The route name.</para>
            /// <remarks>
            /// <para> This parameter is returned only for static routes.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>testname</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryName")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryName { get; set; }

            /// <summary>
            /// <para>The next hop ID. This parameter is not returned if the route is a blackhole route.</para>
            /// 
            /// <b>Example:</b>
            /// <para>tr-attach-vx6iwhjr1x1j78****</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryNextHopId")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryNextHopId { get; set; }

            /// <summary>
            /// <para>The next hop ID.</para>
            /// 
            /// <b>Example:</b>
            /// <para>vpc-m5ent6du8deaq5*****</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryNextHopResourceId")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryNextHopResourceId { get; set; }

            /// <summary>
            /// <para>The next hop type. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>VPC</b></description></item>
            /// <item><description><b>VBR</b></description></item>
            /// <item><description><b>TR</b></description></item>
            /// <item><description><b>VPN</b></description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>VPC</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryNextHopResourceType")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryNextHopResourceType { get; set; }

            /// <summary>
            /// <para>The next hop type. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>BlackHole</b>: a blackhole route. Packets destined for the destination CIDR block of the route are dropped.</description></item>
            /// <item><description><b>Attachment</b>: a network instance connection. Packets destined for the destination CIDR block of the route are forwarded to the specified network instance connection.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>BlackHole</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryNextHopType")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryNextHopType { get; set; }

            /// <summary>
            /// <para>The source instance ID.</para>
            /// 
            /// <b>Example:</b>
            /// <para>vpc-m5ent6du8deaq5*****</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryOriginResourceId")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryOriginResourceId { get; set; }

            /// <summary>
            /// <para>The source instance type. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>VPC</b></description></item>
            /// <item><description><b>VBR</b></description></item>
            /// <item><description><b>TR</b></description></item>
            /// <item><description><b>VPN</b></description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>VPC</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryOriginResourceType")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryOriginResourceType { get; set; }

            /// <summary>
            /// <para>The route status. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>Active</b></description></item>
            /// <item><description><b>Rejected</b></description></item>
            /// <item><description><b>Prohibited</b></description></item>
            /// <item><description><b>Standby</b></description></item>
            /// <item><description><b>Candidate</b></description></item>
            /// <item><description><b>Creating</b></description></item>
            /// <item><description><b>Deleting</b></description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>Active</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryStatus")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryStatus { get; set; }

            /// <summary>
            /// <para>The type of the route. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>Static</b>: static routes.</description></item>
            /// <item><description><b>Propagated</b>: automatically learned by the route table.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>Static</para>
            /// </summary>
            [NameInMap("TransitRouterRouteEntryType")]
            [Validation(Required=false)]
            public string TransitRouterRouteEntryType { get; set; }

        }

    }

}
