// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Kvcachestore20260617.Models
{
    public class CreateKVCacheStoreResponseBody : TeaModel {
        /// <summary>
        /// <para>The ID of the newly created KVCacheStore.</para>
        /// 
        /// <b>Example:</b>
        /// <para>kvs-xxxxx</para>
        /// </summary>
        [NameInMap("KvcsId")]
        [Validation(Required=false)]
        public string KvcsId { get; set; }

        /// <summary>
        /// <para>The order ID generated by this creation request.</para>
        /// 
        /// <b>Example:</b>
        /// <para>order-xxxxx</para>
        /// </summary>
        [NameInMap("OrderId")]
        [Validation(Required=false)]
        public string OrderId { get; set; }

        /// <summary>
        /// <para>The request ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>API-a6e81d15-1b36-4d37-ad61-593531e7fa58</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
