// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class DescribeInstanceStatisticsResponseBody : TeaModel {
        /// <summary>
        /// <para>The risk information about assets.</para>
        /// </summary>
        [NameInMap("Data")]
        [Validation(Required=false)]
        public List<DescribeInstanceStatisticsResponseBodyData> Data { get; set; }
        public class DescribeInstanceStatisticsResponseBodyData : TeaModel {
            /// <summary>
            /// <para>The number of unusual logons to the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>0</para>
            /// </summary>
            [NameInMap("Account")]
            [Validation(Required=false)]
            public int? Account { get; set; }

            /// <summary>
            /// <para>The number of alerts generated by the agentless detection feature.</para>
            /// 
            /// <b>Example:</b>
            /// <para>13</para>
            /// </summary>
            [NameInMap("AgentlessAll")]
            [Validation(Required=false)]
            public int? AgentlessAll { get; set; }

            /// <summary>
            /// <para>The number of baseline risks detected by the agentless detection feature.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("AgentlessBaseline")]
            [Validation(Required=false)]
            public int? AgentlessBaseline { get; set; }

            /// <summary>
            /// <para>The number of malicious samples detected by the agentless detection feature.</para>
            /// 
            /// <b>Example:</b>
            /// <para>3</para>
            /// </summary>
            [NameInMap("AgentlessMalicious")]
            [Validation(Required=false)]
            public int? AgentlessMalicious { get; set; }

            /// <summary>
            /// <para>The number of sensitive file alerts generated by the agentless detection feature.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("AgentlessSensitiveFile")]
            [Validation(Required=false)]
            public int? AgentlessSensitiveFile { get; set; }

            /// <summary>
            /// <para>The number of system vulnerabilities detected by the agentless detection feature.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("AgentlessVulCve")]
            [Validation(Required=false)]
            public int? AgentlessVulCve { get; set; }

            /// <summary>
            /// <para>The number of application vulnerabilities detected by the agentless detection feature.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("AgentlessVulSca")]
            [Validation(Required=false)]
            public int? AgentlessVulSca { get; set; }

            /// <summary>
            /// <para>The number of Windows vulnerabilities detected by using agentless detection.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("AgentlessVulSys")]
            [Validation(Required=false)]
            public int? AgentlessVulSys { get; set; }

            /// <summary>
            /// <para>The number of application vulnerabilities detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("AppNum")]
            [Validation(Required=false)]
            public int? AppNum { get; set; }

            /// <summary>
            /// <para>The number of Web-CMS vulnerabilities detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>5</para>
            /// </summary>
            [NameInMap("CmsNum")]
            [Validation(Required=false)]
            public int? CmsNum { get; set; }

            /// <summary>
            /// <para>Number of high-risk CSPM issues in the system</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("CspmHighRiskNum")]
            [Validation(Required=false)]
            public string CspmHighRiskNum { get; set; }

            /// <summary>
            /// <para>The number of configuration risks detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("CspmNum")]
            [Validation(Required=false)]
            public int? CspmNum { get; set; }

            /// <summary>
            /// <para>The number of common vulnerabilities detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("CveNum")]
            [Validation(Required=false)]
            public int? CveNum { get; set; }

            /// <summary>
            /// <para>The number of urgent vulnerabilities detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>6</para>
            /// </summary>
            [NameInMap("EmgNum")]
            [Validation(Required=false)]
            public int? EmgNum { get; set; }

            /// <summary>
            /// <para>The number of baseline risks detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("Health")]
            [Validation(Required=false)]
            public int? Health { get; set; }

            /// <summary>
            /// <para>Number of security alerts for asset existence reminders.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("RemindSuspiciousNum")]
            [Validation(Required=false)]
            public string RemindSuspiciousNum { get; set; }

            /// <summary>
            /// <para>The number of middleware vulnerabilities detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("ScaNum")]
            [Validation(Required=false)]
            public int? ScaNum { get; set; }

            /// <summary>
            /// <para>Number of high-risk security alerts for the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("SeriousSuspiciousNum")]
            [Validation(Required=false)]
            public string SeriousSuspiciousNum { get; set; }

            /// <summary>
            /// <para>Number of suspicious security alerts for the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("SuspectSuspiciousNum")]
            [Validation(Required=false)]
            public string SuspectSuspiciousNum { get; set; }

            /// <summary>
            /// <para>The number of alerts generated for the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("Suspicious")]
            [Validation(Required=false)]
            public int? Suspicious { get; set; }

            /// <summary>
            /// <para>Number of system vulnerabilities in the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("SysAsapVulCount")]
            [Validation(Required=false)]
            public string SysAsapVulCount { get; set; }

            /// <summary>
            /// <para>The number of Windows system vulnerabilities detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>3</para>
            /// </summary>
            [NameInMap("SysNum")]
            [Validation(Required=false)]
            public int? SysNum { get; set; }

            /// <summary>
            /// <para>The number of trojans detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("Trojan")]
            [Validation(Required=false)]
            public int? Trojan { get; set; }

            /// <summary>
            /// <para>The UUID of the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>6690a46c-0edb-4663-a641-3629d1a9****</para>
            /// </summary>
            [NameInMap("Uuid")]
            [Validation(Required=false)]
            public string Uuid { get; set; }

            /// <summary>
            /// <para>The total number of vulnerabilities detected on the asset.</para>
            /// 
            /// <b>Example:</b>
            /// <para>17</para>
            /// </summary>
            [NameInMap("Vul")]
            [Validation(Required=false)]
            public int? Vul { get; set; }

            /// <summary>
            /// <para>The number of weak passwords.</para>
            /// 
            /// <b>Example:</b>
            /// <para>22</para>
            /// </summary>
            [NameInMap("WeakPWNum")]
            [Validation(Required=false)]
            public int? WeakPWNum { get; set; }

        }

        /// <summary>
        /// <para>The ID of the request, which is used to locate and troubleshoot issues.</para>
        /// 
        /// <b>Example:</b>
        /// <para>8F035A9D-D19F-5430-8CA5-1497991B7C61</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
