// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class DescribeClusterScannerListResponseBody : TeaModel {
        /// <summary>
        /// <para>Number of clusters with installed scanners.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("InstalledCount")]
        [Validation(Required=false)]
        public int? InstalledCount { get; set; }

        /// <summary>
        /// <para>List of clusters.</para>
        /// </summary>
        [NameInMap("List")]
        [Validation(Required=false)]
        public List<DescribeClusterScannerListResponseBodyList> List { get; set; }
        public class DescribeClusterScannerListResponseBodyList : TeaModel {
            /// <summary>
            /// <para>Latest heartbeat time.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1693446913000</para>
            /// </summary>
            [NameInMap("LastTime")]
            [Validation(Required=false)]
            public long? LastTime { get; set; }

            /// <summary>
            /// <para>Whether an update is needed.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("NeedUpdate")]
            [Validation(Required=false)]
            public bool? NeedUpdate { get; set; }

            /// <summary>
            /// <para>Scanner status. Values:</para>
            /// <list type="bullet">
            /// <item><description><b>online</b>: Running</description></item>
            /// <item><description><b>offline</b>: Offline</description></item>
            /// <item><description><b>not_installed</b>: Not Installed</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>offline</para>
            /// </summary>
            [NameInMap("Status")]
            [Validation(Required=false)]
            public string Status { get; set; }

            /// <summary>
            /// <para>Version number.</para>
            /// 
            /// <b>Example:</b>
            /// <para>20241111</para>
            /// </summary>
            [NameInMap("Version")]
            [Validation(Required=false)]
            public string Version { get; set; }

            /// <summary>
            /// <para>Whether the incremental scan switch is enabled. Values: </para>
            /// <list type="bullet">
            /// <item><description><b>0</b>: Not enabled</description></item>
            /// <item><description><b>1</b>: Enabled</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("WebhookOpen")]
            [Validation(Required=false)]
            public int? WebhookOpen { get; set; }

            /// <summary>
            /// <para>The incremental scan component status. Values: </para>
            /// <list type="bullet">
            /// <item><description><b>n</b>: Not deployed </description></item>
            /// <item><description><b>y</b>: Deployed</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>n</para>
            /// </summary>
            [NameInMap("WebhookStatus")]
            [Validation(Required=false)]
            public string WebhookStatus { get; set; }

        }

        /// <summary>
        /// <para>The ID of this request, generated by Alibaba Cloud as a unique identifier, which can be used for troubleshooting and problem localization.</para>
        /// 
        /// <b>Example:</b>
        /// <para>11C96623-E106-59C9-866D-A6C82911459F</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
