// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class DescribeSecurityCheckScheduleConfigResponseBody : TeaModel {
        /// <summary>
        /// <para>The request ID. It is a unique identifier generated by Alibaba Cloud for the request and can be used for troubleshooting.</para>
        /// 
        /// <b>Example:</b>
        /// <para>48D2E9A9-A1B0-4295-B727-0995757C47E9</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>The detailed configuration of the custom check settings.</para>
        /// </summary>
        [NameInMap("RiskCheckJobConfig")]
        [Validation(Required=false)]
        public DescribeSecurityCheckScheduleConfigResponseBodyRiskCheckJobConfig RiskCheckJobConfig { get; set; }
        public class DescribeSecurityCheckScheduleConfigResponseBodyRiskCheckJobConfig : TeaModel {
            /// <summary>
            /// <para>The check cycle. Valid values: Monday to Sunday. You can specify multiple days. Separate multiple days with commas (,).</para>
            /// <list type="bullet">
            /// <item><description><b>1</b>: Monday</description></item>
            /// <item><description><b>2</b>: Tuesday</description></item>
            /// <item><description><b>3</b>: Wednesday</description></item>
            /// <item><description><b>4</b>: Thursday</description></item>
            /// <item><description><b>5</b>: Friday</description></item>
            /// <item><description><b>6</b>: Saturday</description></item>
            /// <item><description><b>7</b>: Sunday</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1,2,3</para>
            /// </summary>
            [NameInMap("DaysOfWeek")]
            [Validation(Required=false)]
            public string DaysOfWeek { get; set; }

            /// <summary>
            /// <para>The check end time.</para>
            /// <list type="bullet">
            /// <item><description><b>6</b>: The check ends between 00:00 and 06:00.</description></item>
            /// <item><description><b>12</b>: The check ends between 06:00 and 12:00.</description></item>
            /// <item><description><b>18</b>: The check ends between 12:00 and 18:00.</description></item>
            /// <item><description><b>24</b>: The check ends between 18:00 and 24:00.</description></item>
            /// </list>
            /// <para>Unit: hours. The value is an on-the-hour value of the current day (0 to 24).</para>
            /// 
            /// <b>Example:</b>
            /// <para>12</para>
            /// </summary>
            [NameInMap("EndTime")]
            [Validation(Required=false)]
            public int? EndTime { get; set; }

            /// <summary>
            /// <para>The check start time.</para>
            /// <list type="bullet">
            /// <item><description><b>0</b>: The check starts between 00:00 and 06:00.</description></item>
            /// <item><description><b>6</b>: The check starts between 06:00 and 12:00.</description></item>
            /// <item><description><b>12</b>: The check starts between 12:00 and 18:00.</description></item>
            /// <item><description><b>18</b>: The check starts between 18:00 and 24:00.</description></item>
            /// </list>
            /// <para>Unit: hours. The value is an on-the-hour value of the current day (0 to 24).</para>
            /// 
            /// <b>Example:</b>
            /// <para>6</para>
            /// </summary>
            [NameInMap("StartTime")]
            [Validation(Required=false)]
            public int? StartTime { get; set; }

        }

    }

}
