// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class DescribeUniRecoverableListResponseBody : TeaModel {
        /// <summary>
        /// <para>The number of recoverable database backup snapshots on the current page.</para>
        /// 
        /// <b>Example:</b>
        /// <para>20</para>
        /// </summary>
        [NameInMap("Count")]
        [Validation(Required=false)]
        public int? Count { get; set; }

        /// <summary>
        /// <para>The current page number when using paging.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("CurrentPage")]
        [Validation(Required=false)]
        public int? CurrentPage { get; set; }

        /// <summary>
        /// <para>The database name.</para>
        /// 
        /// <b>Example:</b>
        /// <para>msdb</para>
        /// </summary>
        [NameInMap("Database")]
        [Validation(Required=false)]
        public string Database { get; set; }

        /// <summary>
        /// <para>The number of recoverable database backup snapshots per page when using paging.</para>
        /// 
        /// <b>Example:</b>
        /// <para>20</para>
        /// </summary>
        [NameInMap("PageSize")]
        [Validation(Required=false)]
        public int? PageSize { get; set; }

        /// <summary>
        /// <para>The list of recoverable database backup snapshots.</para>
        /// </summary>
        [NameInMap("RecoverableInfoList")]
        [Validation(Required=false)]
        public List<DescribeUniRecoverableListResponseBodyRecoverableInfoList> RecoverableInfoList { get; set; }
        public class DescribeUniRecoverableListResponseBodyRecoverableInfoList : TeaModel {
            /// <summary>
            /// <para>The timestamp when the backup started. Unit: milliseconds.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1671468180000</para>
            /// </summary>
            [NameInMap("FirstTime")]
            [Validation(Required=false)]
            public long? FirstTime { get; set; }

            /// <summary>
            /// <para>The timestamp of the latest backup. Unit: milliseconds.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1671468180000</para>
            /// </summary>
            [NameInMap("LastTime")]
            [Validation(Required=false)]
            public long? LastTime { get; set; }

            /// <summary>
            /// <para>The <b>reset_scn</b> value of the selected record in the recoverable point-in-time query for an Oracle database backup.</para>
            /// 
            /// <b>Example:</b>
            /// <para>4529940.0</para>
            /// </summary>
            [NameInMap("ResetScn")]
            [Validation(Required=false)]
            public string ResetScn { get; set; }

            /// <summary>
            /// <para>The <b>reset_time</b> value of the selected record in the recoverable point-in-time query for an Oracle database backup.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2021-01-30 08:04:36</para>
            /// </summary>
            [NameInMap("ResetTime")]
            [Validation(Required=false)]
            public long? ResetTime { get; set; }

            /// <summary>
            /// <para>The database restoration information when the database type is MSSQL. The value is a JSON string. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>name</b>: the database name.</description></item>
            /// <item><description><b>files</b>: the database file path.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>{
            ///       &quot;files&quot;: {
            ///             &quot;qtc&quot;: &quot;F:\\database\\qtc.mdf&quot;,
            ///             &quot;qtc_log&quot;: &quot;F:\\database\\qtc_0.ldf&quot;
            ///       },
            ///       &quot;name&quot;: &quot;qtc&quot;
            /// }</para>
            /// </summary>
            [NameInMap("RestoreInfo")]
            [Validation(Required=false)]
            public string RestoreInfo { get; set; }

        }

        /// <summary>
        /// <para>The request ID, which is a unique identifier generated by Alibaba Cloud for this request. You can use it to troubleshoot issues.</para>
        /// 
        /// <b>Example:</b>
        /// <para>F35F45B0-5D6B-4238-BE02-A62D0760****</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>The total number of recoverable database backup snapshots.</para>
        /// 
        /// <b>Example:</b>
        /// <para>23</para>
        /// </summary>
        [NameInMap("TotalCount")]
        [Validation(Required=false)]
        public int? TotalCount { get; set; }

    }

}
