// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class DescribeStrictEventNameResponseBody : TeaModel {
        /// <summary>
        /// <para>Returned data.</para>
        /// </summary>
        [NameInMap("Data")]
        [Validation(Required=false)]
        public List<DescribeStrictEventNameResponseBodyData> Data { get; set; }
        public class DescribeStrictEventNameResponseBodyData : TeaModel {
            /// <summary>
            /// <para>Alarm name.</para>
            /// 
            /// <b>Example:</b>
            /// <para>System log abnormal deletion</para>
            /// </summary>
            [NameInMap("EventName")]
            [Validation(Required=false)]
            public string EventName { get; set; }

            /// <summary>
            /// <para>Alarm type.</para>
            /// 
            /// <b>Example:</b>
            /// <para>Suspicious Process</para>
            /// </summary>
            [NameInMap("EventType")]
            [Validation(Required=false)]
            public string EventType { get; set; }

            /// <summary>
            /// <para>Displayed alarm name.</para>
            /// 
            /// <b>Example:</b>
            /// <para>Suspicious Process</para>
            /// </summary>
            [NameInMap("ShowEventName")]
            [Validation(Required=false)]
            public string ShowEventName { get; set; }

            /// <summary>
            /// <para>Displayed alarm type.</para>
            /// 
            /// <b>Example:</b>
            /// <para>System log abnormal deletion</para>
            /// </summary>
            [NameInMap("ShowEventType")]
            [Validation(Required=false)]
            public string ShowEventType { get; set; }

            /// <summary>
            /// <para>Indicates whether the user has enabled the strict mode for this alarm type.</para>
            /// <list type="bullet">
            /// <item><description>true: Enabled</description></item>
            /// <item><description>false: Not enabled</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("SwitchConfig")]
            [Validation(Required=false)]
            public bool? SwitchConfig { get; set; }

        }

        /// <summary>
        /// <para>The ID of this call request, a unique identifier generated by Alibaba Cloud for this request, which can be used to troubleshoot and locate issues.</para>
        /// 
        /// <b>Example:</b>
        /// <para>D65AADFC-1D20-5A6A-8F6A-9FA53C0D****</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
