// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class DescribeExposedStatisticsResponseBody : TeaModel {
        /// <summary>
        /// <para>The total number of high-risk vulnerabilities that are exposed on the Internet and can be exploited by hackers.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("ExposedAsapVulCount")]
        [Validation(Required=false)]
        public int? ExposedAsapVulCount { get; set; }

        /// <summary>
        /// <para>The total number of system components (such as OpenSSL and OpenSSH) on your servers that are exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>7</para>
        /// </summary>
        [NameInMap("ExposedComponentCount")]
        [Validation(Required=false)]
        public int? ExposedComponentCount { get; set; }

        /// <summary>
        /// <para>The number of ApsaraDB for MongoDB database assets exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("ExposedDdsCount")]
        [Validation(Required=false)]
        public int? ExposedDdsCount { get; set; }

        /// <summary>
        /// <para>The number of ECS assets exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>5</para>
        /// </summary>
        [NameInMap("ExposedEcsCount")]
        [Validation(Required=false)]
        public int? ExposedEcsCount { get; set; }

        /// <summary>
        /// <para>The total number of assets exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>10</para>
        /// </summary>
        [NameInMap("ExposedInstanceCount")]
        [Validation(Required=false)]
        public int? ExposedInstanceCount { get; set; }

        /// <summary>
        /// <para>The total number of IP addresses exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>100</para>
        /// </summary>
        [NameInMap("ExposedIpCount")]
        [Validation(Required=false)]
        public int? ExposedIpCount { get; set; }

        /// <summary>
        /// <para>The number of ApsaraDB for Redis database assets exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>3</para>
        /// </summary>
        [NameInMap("ExposedKvstoreCount")]
        [Validation(Required=false)]
        public int? ExposedKvstoreCount { get; set; }

        /// <summary>
        /// <para>The total number of medium-risk vulnerabilities that are exposed on the Internet and can be exploited by hackers.</para>
        /// 
        /// <b>Example:</b>
        /// <para>5</para>
        /// </summary>
        [NameInMap("ExposedLaterVulCount")]
        [Validation(Required=false)]
        public int? ExposedLaterVulCount { get; set; }

        /// <summary>
        /// <para>The total number of low-risk vulnerabilities that are exposed on the Internet and can be exploited by hackers.</para>
        /// 
        /// <b>Example:</b>
        /// <para>0</para>
        /// </summary>
        [NameInMap("ExposedNntfVulCount")]
        [Validation(Required=false)]
        public int? ExposedNntfVulCount { get; set; }

        /// <summary>
        /// <para>The total number of ports exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>6</para>
        /// </summary>
        [NameInMap("ExposedPortCount")]
        [Validation(Required=false)]
        public int? ExposedPortCount { get; set; }

        /// <summary>
        /// <para>The number of RDS database assets exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("ExposedRdsCount")]
        [Validation(Required=false)]
        public int? ExposedRdsCount { get; set; }

        /// <summary>
        /// <para>The total number of system keys on your servers that are exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>20</para>
        /// </summary>
        [NameInMap("ExposedWeekPasswordMachineCount")]
        [Validation(Required=false)]
        public int? ExposedWeekPasswordMachineCount { get; set; }

        /// <summary>
        /// <para>The total number of gateway assets (Server Load Balancer and NAT Gateway) exposed on the Internet.</para>
        /// 
        /// <b>Example:</b>
        /// <para>3</para>
        /// </summary>
        [NameInMap("GatewayAssetCount")]
        [Validation(Required=false)]
        public int? GatewayAssetCount { get; set; }

        /// <summary>
        /// <para>The ID of this request, which is a unique identifier generated by Alibaba Cloud for the request. It can be used to troubleshoot and locate issues.</para>
        /// 
        /// <b>Example:</b>
        /// <para>4B897D10-B3CD-4A93-A5FA-591F3ED12A86</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
