// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class GetPropertyScheduleConfigResponseBody : TeaModel {
        /// <summary>
        /// <para>The collection cycle configuration of Asset Fingerprints.</para>
        /// </summary>
        [NameInMap("PropertyScheduleConfig")]
        [Validation(Required=false)]
        public GetPropertyScheduleConfigResponseBodyPropertyScheduleConfig PropertyScheduleConfig { get; set; }
        public class GetPropertyScheduleConfigResponseBodyPropertyScheduleConfig : TeaModel {
            /// <summary>
            /// <para>The estimated timestamp when the next Asset Fingerprints collection starts. Unit: milliseconds.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1671630647018</para>
            /// </summary>
            [NameInMap("NextScheduleTime")]
            [Validation(Required=false)]
            public long? NextScheduleTime { get; set; }

            /// <summary>
            /// <para>The collection frequency of Asset Fingerprints. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>0</b>: Disabled. Periodic automatic collection of Asset Fingerprints is not performed.</description></item>
            /// <item><description><b>1</b>: Collected once every hour.</description></item>
            /// <item><description><b>3</b>: Collected once every 3 hours.</description></item>
            /// <item><description><b>12</b>: Collected once every 12 hours.</description></item>
            /// <item><description><b>24</b>: Collected once every day.</description></item>
            /// <item><description><b>168</b>: Collected once every 7 days.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>3</para>
            /// </summary>
            [NameInMap("ScheduleTime")]
            [Validation(Required=false)]
            public string ScheduleTime { get; set; }

            /// <summary>
            /// <para>The type of Asset Fingerprints for which the automatic collection frequency is configured. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>scheduler_port_period</b>: listening port</description></item>
            /// <item><description><b>scheduler_process_period</b>: running process</description></item>
            /// <item><description><b>scheduler_account_period</b>: account asset</description></item>
            /// <item><description><b>scheduler_software_period</b>: software asset</description></item>
            /// <item><description><b>scheduler_cron_period</b>: scheduled node</description></item>
            /// <item><description><b>scheduler_sca_period</b>: middleware</description></item>
            /// <item><description><b>scheduler_autorun_period</b>: startup item</description></item>
            /// <item><description><b>scheduler_lkm_period</b>: kernel module</description></item>
            /// <item><description><b>scheduler_sca_proxy_period</b>: website</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>scheduler_account_period</para>
            /// </summary>
            [NameInMap("Type")]
            [Validation(Required=false)]
            public string Type { get; set; }

        }

        /// <summary>
        /// <para>The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.</para>
        /// 
        /// <b>Example:</b>
        /// <para>B37C9052-A73E-4707-A024-92477028****</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
