// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class ListFileProtectClientRuleFileTypeResponseBody : TeaModel {
        /// <summary>
        /// <para>The protected file types.</para>
        /// </summary>
        [NameInMap("FileTypes")]
        [Validation(Required=false)]
        public List<string> FileTypes { get; set; }

        /// <summary>
        /// <para>The ID of the request. The ID is generated by Alibaba Cloud and is unique. You can use the ID to troubleshoot issues.</para>
        /// 
        /// <b>Example:</b>
        /// <para>F8B6F758-BCD4-597A-8A2C-DA5A552C****</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
