// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class OpenBackupAutoConfigRequest : TeaModel {
        /// <summary>
        /// <para>The number of servers specified in a batch of anti-ransomware policies that are automatically generated by the managed anti-ransomware feature.</para>
        /// <remarks>
        /// <para> The maximum value is 50. If the number of specified servers exceeds 50, the value 50 is used.</para>
        /// </remarks>
        /// 
        /// <b>Example:</b>
        /// <para>20</para>
        /// </summary>
        [NameInMap("MaxBatchSize")]
        [Validation(Required=false)]
        public int? MaxBatchSize { get; set; }

    }

}
