// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Sas20181203.Models
{
    public class UpdateSelectionKeyByTypeRequest : TeaModel {
        /// <summary>
        /// The business type of the asset selection. Valid value:
        /// 
        /// *   **VIRUS_SCAN_CYCLE_CONFIG**: virus detection configuration.
        /// *   **VIRUS_SCAN_ONCE_TASK**: one-time scan for virus detection.
        /// *   **AGENTLESS_MALICIOUS_WHITE_LIST_[ID]**: a whitelist rule for alerts that are generated by the agentless detection feature.
        /// *   **AGENTLESS_VUL_WHITE_LIST_[ID]**: a whitelist rule for vulnerabilities that are detected by the agentless detection feature.
        /// *   **FILE_PROTECT_RULE_SWITCH_TYPE_[ID]**: key file protection.
        /// </summary>
        [NameInMap("BusinessType")]
        [Validation(Required=false)]
        public string BusinessType { get; set; }

        /// <summary>
        /// The unique identifier of the asset selection.
        /// </summary>
        [NameInMap("SelectionKey")]
        [Validation(Required=false)]
        public string SelectionKey { get; set; }

    }

}
