// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Alidns20150109.Models
{
    public class VerifyAtiAgentDnsRecordsResponseBody : TeaModel {
        /// <summary>
        /// <para>The details about the access denial. This field is returned only when RAM authentication fails.</para>
        /// </summary>
        [NameInMap("AccessDeniedDetail")]
        [Validation(Required=false)]
        public VerifyAtiAgentDnsRecordsResponseBodyAccessDeniedDetail AccessDeniedDetail { get; set; }
        public class VerifyAtiAgentDnsRecordsResponseBodyAccessDeniedDetail : TeaModel {
            /// <summary>
            /// <para>The unauthorized operation that was attempted.</para>
            /// 
            /// <b>Example:</b>
            /// <para>AddRspDomainServerHoldStatusForGatewayOte</para>
            /// </summary>
            [NameInMap("AuthAction")]
            [Validation(Required=false)]
            public string AuthAction { get; set; }

            /// <summary>
            /// <para>The display name of the authorization principal.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2015555733387XXXX</para>
            /// </summary>
            [NameInMap("AuthPrincipalDisplayName")]
            [Validation(Required=false)]
            public string AuthPrincipalDisplayName { get; set; }

            /// <summary>
            /// <para>The owner ID of the authorization principal.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1046973331XXXX</para>
            /// </summary>
            [NameInMap("AuthPrincipalOwnerId")]
            [Validation(Required=false)]
            public string AuthPrincipalOwnerId { get; set; }

            /// <summary>
            /// <para>The identity type.</para>
            /// 
            /// <b>Example:</b>
            /// <para>SubUser</para>
            /// </summary>
            [NameInMap("AuthPrincipalType")]
            [Validation(Required=false)]
            public string AuthPrincipalType { get; set; }

            /// <summary>
            /// <para>The encoded complete diagnostic message.</para>
            /// 
            /// <b>Example:</b>
            /// <para>AQEAAAAAaNIARXXXXUQwNjE0LUQzN0XXXXVEQy1BQzExLTMzXXXXNTkxRjk1Ng==</para>
            /// </summary>
            [NameInMap("EncodedDiagnosticMessage")]
            [Validation(Required=false)]
            public string EncodedDiagnosticMessage { get; set; }

            /// <summary>
            /// <para>The reason for the authentication failure. Valid values:</para>
            /// <list type="bullet">
            /// <item><description>ExplicitDeny: explicit deny.</description></item>
            /// <item><description>ImplicitDeny: implicit deny.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>ImplicitDeny</para>
            /// </summary>
            [NameInMap("NoPermissionType")]
            [Validation(Required=false)]
            public string NoPermissionType { get; set; }

            /// <summary>
            /// <para>The policy type.</para>
            /// 
            /// <b>Example:</b>
            /// <para>DlpSend</para>
            /// </summary>
            [NameInMap("PolicyType")]
            [Validation(Required=false)]
            public string PolicyType { get; set; }

        }

        /// <summary>
        /// <para>The Agent registration ID. This ID is automatically generated by the Alibaba Cloud ATS platform and is globally unique within the platform.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2074753647748672512</para>
        /// </summary>
        [NameInMap("AgentRegisterInfoId")]
        [Validation(Required=false)]
        public string AgentRegisterInfoId { get; set; }

        /// <summary>
        /// <para>The Agent status.</para>
        /// 
        /// <b>Example:</b>
        /// <para>活跃</para>
        /// </summary>
        [NameInMap("AgentStatus")]
        [Validation(Required=false)]
        public string AgentStatus { get; set; }

        /// <summary>
        /// <para>Indicates whether all DNS records have been verified.</para>
        /// 
        /// <b>Example:</b>
        /// <para>true</para>
        /// </summary>
        [NameInMap("AllVerified")]
        [Validation(Required=false)]
        public bool? AllVerified { get; set; }

        /// <summary>
        /// <para>The request ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>B57C121B-A45F-44D8-A9B2-XXXXXXX</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        [NameInMap("Results")]
        [Validation(Required=false)]
        public VerifyAtiAgentDnsRecordsResponseBodyResults Results { get; set; }
        public class VerifyAtiAgentDnsRecordsResponseBodyResults : TeaModel {
            [NameInMap("Result")]
            [Validation(Required=false)]
            public List<VerifyAtiAgentDnsRecordsResponseBodyResultsResult> Result { get; set; }
            public class VerifyAtiAgentDnsRecordsResponseBodyResultsResult : TeaModel {
                [NameInMap("FailReason")]
                [Validation(Required=false)]
                public string FailReason { get; set; }

                [NameInMap("RecordName")]
                [Validation(Required=false)]
                public string RecordName { get; set; }

                [NameInMap("RecordType")]
                [Validation(Required=false)]
                public string RecordType { get; set; }

                [NameInMap("VerifyStatus")]
                [Validation(Required=false)]
                public string VerifyStatus { get; set; }

            }

        }

        /// <summary>
        /// <para>Indicates whether the operation to delete the domain name instance configuration is successful. Valid values:</para>
        /// <list type="bullet">
        /// <item><description><para>true: The operation is successful.</para>
        /// </description></item>
        /// <item><description><para>false: The operation failed.</para>
        /// </description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>true</para>
        /// </summary>
        [NameInMap("Success")]
        [Validation(Required=false)]
        public bool? Success { get; set; }

    }

}
