// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Dts20200101.Models
{
    public class DescribeSubscriptionInstanceStatusResponseBody : TeaModel {
        /// <summary>
        /// The start of the time range for change tracking. The time is displayed in the *yyyy-MM-dd*T*HH:mm:ss*Z format in UTC.
        /// </summary>
        [NameInMap("BeginTimestamp")]
        [Validation(Required=false)]
        public string BeginTimestamp { get; set; }

        /// <summary>
        /// The consumption checkpoint of the change tracking instance. The time is displayed in the *yyyy-MM-dd*T*HH:mm:ss*Z format in UTC.
        /// </summary>
        [NameInMap("ConsumptionCheckpoint")]
        [Validation(Required=false)]
        public string ConsumptionCheckpoint { get; set; }

        /// <summary>
        /// The downstream client information, in the following format: \\<IP address of the downstream client>:\\<Random ID generated by DTS>.
        /// </summary>
        [NameInMap("ConsumptionClient")]
        [Validation(Required=false)]
        public string ConsumptionClient { get; set; }

        /// <summary>
        /// The end of the time range for change tracking. The time is displayed in the *yyyy-MM-dd*T*HH:mm:ss*Z format in UTC.
        /// </summary>
        [NameInMap("EndTimestamp")]
        [Validation(Required=false)]
        public string EndTimestamp { get; set; }

        /// <summary>
        /// The error code returned if the call failed.
        /// </summary>
        [NameInMap("ErrCode")]
        [Validation(Required=false)]
        public string ErrCode { get; set; }

        /// <summary>
        /// The error message returned if the call failed.
        /// </summary>
        [NameInMap("ErrMessage")]
        [Validation(Required=false)]
        public string ErrMessage { get; set; }

        /// <summary>
        /// The error message returned if change tracking failed.
        /// </summary>
        [NameInMap("ErrorMessage")]
        [Validation(Required=false)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// The billing method of the change tracking instance. Valid values:
        /// 
        /// *   **PrePaid**: subscription
        /// *   **PostPaid**: pay-as-you-go
        /// </summary>
        [NameInMap("PayType")]
        [Validation(Required=false)]
        public string PayType { get; set; }

        /// <summary>
        /// The ID of the request.
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// The connection settings of the source instance.
        /// </summary>
        [NameInMap("SourceEndpoint")]
        [Validation(Required=false)]
        public DescribeSubscriptionInstanceStatusResponseBodySourceEndpoint SourceEndpoint { get; set; }
        public class DescribeSubscriptionInstanceStatusResponseBodySourceEndpoint : TeaModel {
            /// <summary>
            /// The ID of the instance that hosts the source database.
            /// </summary>
            [NameInMap("InstanceID")]
            [Validation(Required=false)]
            public string InstanceID { get; set; }

            /// <summary>
            /// The instance type of the source database.
            /// 
            /// >  This parameter is returned only for change tracking instances of the new version.
            /// </summary>
            [NameInMap("InstanceType")]
            [Validation(Required=false)]
            public string InstanceType { get; set; }

        }

        /// <summary>
        /// The status of the change tracking task. Valid values:
        /// 
        /// *   **NotStarted**: The task is not started.
        /// *   **Prechecking**: The task is being prechecked.
        /// *   **PrecheckFailed**: The task failed to pass the precheck.
        /// *   **Starting**: The task is being started.
        /// *   **Normal**: The task is running as expected.
        /// *   **Abnormal**: The task is not running as expected.
        /// </summary>
        [NameInMap("Status")]
        [Validation(Required=false)]
        public string Status { get; set; }

        /// <summary>
        /// The topic of the change tracking instance.
        /// 
        /// >  This parameter is returned only if your change tracking instance is of the new version and you have called the [CreateConsumerGroup](https://help.aliyun.com/document_detail/122863.html) operation to create a consumer group.
        /// </summary>
        [NameInMap("SubscribeTopic")]
        [Validation(Required=false)]
        public string SubscribeTopic { get; set; }

        /// <summary>
        /// The types of operations that are tracked by the task.
        /// </summary>
        [NameInMap("SubscriptionDataType")]
        [Validation(Required=false)]
        public DescribeSubscriptionInstanceStatusResponseBodySubscriptionDataType SubscriptionDataType { get; set; }
        public class DescribeSubscriptionInstanceStatusResponseBodySubscriptionDataType : TeaModel {
            /// <summary>
            /// Indicates whether data definition language (DDL) operations are tracked. Valid values:
            /// 
            /// *   **true**: yes
            /// *   **false**: no
            /// </summary>
            [NameInMap("DDL")]
            [Validation(Required=false)]
            public bool? DDL { get; set; }

            /// <summary>
            /// Indicates whether data manipulation language (DML) operations are tracked. Valid values:
            /// 
            /// *   **true**: yes
            /// *   **false**: no
            /// </summary>
            [NameInMap("DML")]
            [Validation(Required=false)]
            public bool? DML { get; set; }

        }

        /// <summary>
        /// The endpoint of the change tracking instance.
        /// </summary>
        [NameInMap("SubscriptionHost")]
        [Validation(Required=false)]
        public DescribeSubscriptionInstanceStatusResponseBodySubscriptionHost SubscriptionHost { get; set; }
        public class DescribeSubscriptionInstanceStatusResponseBodySubscriptionHost : TeaModel {
            /// <summary>
            /// The private endpoint of the change tracking instance. The format is `<Address>:<Port number>`.
            /// </summary>
            [NameInMap("PrivateHost")]
            [Validation(Required=false)]
            public string PrivateHost { get; set; }

            /// <summary>
            /// The public endpoint of the change tracking instance. The format is `<Address>:<Port number>`.
            /// </summary>
            [NameInMap("PublicHost")]
            [Validation(Required=false)]
            public string PublicHost { get; set; }

            /// <summary>
            /// The virtual private cloud (VPC) endpoint of the change tracking instance. The format is `<Address>:<Port number>`.
            /// </summary>
            [NameInMap("VPCHost")]
            [Validation(Required=false)]
            public string VPCHost { get; set; }

        }

        /// <summary>
        /// The ID of the change tracking instance.
        /// </summary>
        [NameInMap("SubscriptionInstanceID")]
        [Validation(Required=false)]
        public string SubscriptionInstanceID { get; set; }

        /// <summary>
        /// The name of the change tracking instance.
        /// </summary>
        [NameInMap("SubscriptionInstanceName")]
        [Validation(Required=false)]
        public string SubscriptionInstanceName { get; set; }

        /// <summary>
        /// The objects for change tracking.
        /// </summary>
        [NameInMap("SubscriptionObject")]
        [Validation(Required=false)]
        public DescribeSubscriptionInstanceStatusResponseBodySubscriptionObject SubscriptionObject { get; set; }
        public class DescribeSubscriptionInstanceStatusResponseBodySubscriptionObject : TeaModel {
            [NameInMap("SynchronousObject")]
            [Validation(Required=false)]
            public List<DescribeSubscriptionInstanceStatusResponseBodySubscriptionObjectSynchronousObject> SynchronousObject { get; set; }
            public class DescribeSubscriptionInstanceStatusResponseBodySubscriptionObjectSynchronousObject : TeaModel {
                /// <summary>
                /// The name of the database to which the object belongs.
                /// </summary>
                [NameInMap("DatabaseName")]
                [Validation(Required=false)]
                public string DatabaseName { get; set; }

                /// <summary>
                /// The table name.
                /// </summary>
                [NameInMap("TableList")]
                [Validation(Required=false)]
                public DescribeSubscriptionInstanceStatusResponseBodySubscriptionObjectSynchronousObjectTableList TableList { get; set; }
                public class DescribeSubscriptionInstanceStatusResponseBodySubscriptionObjectSynchronousObjectTableList : TeaModel {
                    [NameInMap("Table")]
                    [Validation(Required=false)]
                    public List<string> Table { get; set; }

                }

                /// <summary>
                /// Indicates whether the data of an entire database is tracked. Valid values:
                /// 
                /// *   **true**: yes
                /// *   **false**: no
                /// </summary>
                [NameInMap("WholeDatabase")]
                [Validation(Required=false)]
                public string WholeDatabase { get; set; }

            }

        }

        /// <summary>
        /// Indicates whether the call was successful.
        /// </summary>
        [NameInMap("Success")]
        [Validation(Required=false)]
        public string Success { get; set; }

        /// <summary>
        /// The ID of the change tracking task.
        /// </summary>
        [NameInMap("TaskId")]
        [Validation(Required=false)]
        public string TaskId { get; set; }

    }

}
