// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Elasticsearch20170613.Models
{
    public class ValidateSlrPermissionRequest : TeaModel {
        /// <summary>
        /// <para>Used to ensure the idempotency of the request. This parameter value is generated by the client and must be unique across different requests, with a maximum length of 64 ASCII characters.</para>
        /// 
        /// <b>Example:</b>
        /// <para>5A2CFF0E-5718-45B5-9D4D-70B3FF****</para>
        /// </summary>
        [NameInMap("ClientToken")]
        [Validation(Required=false)]
        public string ClientToken { get; set; }

        /// <summary>
        /// <para>The service-linked role name. Valid values:</para>
        /// <para>&lt;props=&quot;china&quot;&gt;- AliyunServiceRoleForElasticsearchOps: Performs elastic scaling tasks for a cluster.- AliyunServiceRoleForElasticsearchCollector: Creates and manages Beats collectors.</para>
        /// <para>This parameter is required.</para>
        /// 
        /// <b>Example:</b>
        /// <para>AliyunServiceRoleForElasticsearchCollector</para>
        /// </summary>
        [NameInMap("rolename")]
        [Validation(Required=false)]
        public string Rolename { get; set; }

    }

}
