// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.CloudAPI20160714.Models
{
    public class DescribeDomainResponseBody : TeaModel {
        /// <summary>
        /// <para>The content of the certificate.</para>
        /// 
        /// <b>Example:</b>
        /// <para>xxx</para>
        /// </summary>
        [NameInMap("CertificateBody")]
        [Validation(Required=false)]
        public string CertificateBody { get; set; }

        /// <summary>
        /// <para>The unique ID of the SSL certificate, which is automatically generated by the system.</para>
        /// 
        /// <b>Example:</b>
        /// <para>6EF60BEC-0242-43AF-BB20-270359FB54A7</para>
        /// </summary>
        [NameInMap("CertificateId")]
        [Validation(Required=false)]
        public string CertificateId { get; set; }

        /// <summary>
        /// <para>The name of the SSL certificate.</para>
        /// 
        /// <b>Example:</b>
        /// <para>myCertificate</para>
        /// </summary>
        [NameInMap("CertificateName")]
        [Validation(Required=false)]
        public string CertificateName { get; set; }

        /// <summary>
        /// <para>The private key of the SSL certificate.</para>
        /// 
        /// <b>Example:</b>
        /// <para>xxx</para>
        /// </summary>
        [NameInMap("CertificatePrivateKey")]
        [Validation(Required=false)]
        public string CertificatePrivateKey { get; set; }

        /// <summary>
        /// <para>证书失效时间戳（毫秒）</para>
        /// 
        /// <b>Example:</b>
        /// <para>1704038400000</para>
        /// </summary>
        [NameInMap("CertificateValidEnd")]
        [Validation(Required=false)]
        public long? CertificateValidEnd { get; set; }

        /// <summary>
        /// <para>证书生效时间戳（毫秒）</para>
        /// 
        /// <b>Example:</b>
        /// <para>1672502400000</para>
        /// </summary>
        [NameInMap("CertificateValidStart")]
        [Validation(Required=false)]
        public long? CertificateValidStart { get; set; }

        /// <summary>
        /// <para>The binding status of the custom domain name. Valid values:</para>
        /// <list type="bullet">
        /// <item><description>BINDING: The domain name has been bound.</description></item>
        /// <item><description>BOUND: The domain name has not been bound.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>BINDING</para>
        /// </summary>
        [NameInMap("DomainBindingStatus")]
        [Validation(Required=false)]
        public string DomainBindingStatus { get; set; }

        /// <summary>
        /// <para>The domain name resolution status. Valid values:</para>
        /// <list type="bullet">
        /// <item><description>RESOLVED: The domain name has been resolved.</description></item>
        /// <item><description>UNRESOLVED: The domain name has not been resolved.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>RESOLVED</para>
        /// </summary>
        [NameInMap("DomainCNAMEStatus")]
        [Validation(Required=false)]
        public string DomainCNAMEStatus { get; set; }

        /// <summary>
        /// <para>The validity status of the domain name. Valid values:</para>
        /// <list type="bullet">
        /// <item><description>NORMAL</description></item>
        /// <item><description>ABNORMAL: This status affects API calls and must be resolved as soon as possible.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>NORMAL</para>
        /// </summary>
        [NameInMap("DomainLegalStatus")]
        [Validation(Required=false)]
        public string DomainLegalStatus { get; set; }

        /// <summary>
        /// <para>The custom domain name.</para>
        /// 
        /// <b>Example:</b>
        /// <para>api.demo.com</para>
        /// </summary>
        [NameInMap("DomainName")]
        [Validation(Required=false)]
        public string DomainName { get; set; }

        /// <summary>
        /// <para>Remarks about the domain name, such as the cause of an exception.</para>
        /// 
        /// <b>Example:</b>
        /// <para>The domain name does not have an ICP filing.</para>
        /// </summary>
        [NameInMap("DomainRemark")]
        [Validation(Required=false)]
        public string DomainRemark { get; set; }

        /// <summary>
        /// <para>The status of the domain name that uses WebSocket.</para>
        /// 
        /// <b>Example:</b>
        /// <para>NORMAL</para>
        /// </summary>
        [NameInMap("DomainWebSocketStatus")]
        [Validation(Required=false)]
        public string DomainWebSocketStatus { get; set; }

        /// <summary>
        /// <para>The ID of the API group. This ID is generated by the system and globally unique.</para>
        /// 
        /// <b>Example:</b>
        /// <para>927d50c0f2e54b359919923d908bb015</para>
        /// </summary>
        [NameInMap("GroupId")]
        [Validation(Required=false)]
        public string GroupId { get; set; }

        /// <summary>
        /// <para>The ID of the request.</para>
        /// 
        /// <b>Example:</b>
        /// <para>6EF60BEC-0242-43AF-BB20-270359FB54A7</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>The second-level domain name that is automatically assigned to the API group.</para>
        /// 
        /// <b>Example:</b>
        /// <para>xxx-cn-hangzhou.alicloudapi.com</para>
        /// </summary>
        [NameInMap("SubDomain")]
        [Validation(Required=false)]
        public string SubDomain { get; set; }

    }

}
