// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.CloudAPI20160714.Models
{
    public class SetDomainRequest : TeaModel {
        /// <summary>
        /// The environment which you can access by using the domain name. If you do not specify this parameter, the domain name can be used to access all environments.
        /// 
        /// If you specify an environment, the domain name can be used to access only the specified environment. Valid values:
        /// 
        /// *   TEST
        /// *   PRE
        /// *   RELEASE
        /// 
        /// If you want to use the domain name to access all environments, set this parameter to an empty string ("").
        /// </summary>
        [NameInMap("BindStageName")]
        [Validation(Required=false)]
        public string BindStageName { get; set; }

        /// <summary>
        /// The network type of the domain name to be bound. Default value: INTERNET. Valid values:
        /// 
        /// *   INTERNET
        /// *   INTRANET. If you set this parameter to this value, the domain name cannot be used on the Internet.
        /// </summary>
        [NameInMap("CustomDomainType")]
        [Validation(Required=false)]
        public string CustomDomainType { get; set; }

        /// <summary>
        /// The custom domain name.
        /// </summary>
        [NameInMap("DomainName")]
        [Validation(Required=false)]
        public string DomainName { get; set; }

        /// <summary>
        /// The ID of the API group. This ID is generated by the system and globally unique.
        /// </summary>
        [NameInMap("GroupId")]
        [Validation(Required=false)]
        public string GroupId { get; set; }

        /// <summary>
        /// Specifies whether this binding relationship takes precedence over the binding relationships between the domain name and other API groups. If you set this parameter to true, this binding relationship takes precedence, and the domain name is automatically unbound from other API groups. This operation brings risks. Proceed with caution.
        /// </summary>
        [NameInMap("IsForce")]
        [Validation(Required=false)]
        public bool? IsForce { get; set; }

        /// <summary>
        /// Specifies whether to redirect HTTP requests to HTTPS requests.
        /// </summary>
        [NameInMap("IsHttpRedirectToHttps")]
        [Validation(Required=false)]
        public bool? IsHttpRedirectToHttps { get; set; }

    }

}
