// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.AgentRetailVision20260506.Models
{
    public class GenerateGroupImageShrinkRequest : TeaModel {
        /// <summary>
        /// <para>The key used for callback signature verification.</para>
        /// 
        /// <b>Example:</b>
        /// <para>your_secret_key</para>
        /// </summary>
        [NameInMap("CallbackSecret")]
        [Validation(Required=false)]
        public string CallbackSecret { get; set; }

        /// <summary>
        /// <para>The callback URL of the customer.</para>
        /// 
        /// <b>Example:</b>
        /// <para><a href="https://xxx.com">https://xxx.com</a></para>
        /// </summary>
        [NameInMap("CallbackUrl")]
        [Validation(Required=false)]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// <para>The composite image request ID generated by the caller.</para>
        /// 
        /// <b>Example:</b>
        /// <para>a5561c14-b5cd-49a4-ab79-01a63b10d99c</para>
        /// </summary>
        [NameInMap("GroupId")]
        [Validation(Required=false)]
        public string GroupId { get; set; }

        /// <summary>
        /// <para>The composite image type. Valid values:</para>
        /// <list type="bullet">
        /// <item><description>1: single-SKU multi-image composite.</description></item>
        /// <item><description>2: multi-SKU composite.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("GroupType")]
        [Validation(Required=false)]
        public int? GroupType { get; set; }

        /// <summary>
        /// <para>The list of platform item IDs, corresponding to smart_retail_item.platform_item_id.</para>
        /// </summary>
        [NameInMap("PlatformItemIdList")]
        [Validation(Required=false)]
        public string PlatformItemIdListShrink { get; set; }

    }

}
