// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Eiam20211201.Models
{
    public class UpdateIdentityProviderRequest : TeaModel {
        /// <summary>
        /// <para>The client token that is used to ensure the idempotency of the request. The value of this parameter is generated by the client to ensure uniqueness among different requests.</para>
        /// 
        /// <b>Example:</b>
        /// <para>client-examplexxx</para>
        /// </summary>
        [NameInMap("ClientToken")]
        [Validation(Required=false)]
        public string ClientToken { get; set; }

        /// <summary>
        /// <para>DingTalk configuration basic information.</para>
        /// </summary>
        [NameInMap("DingtalkAppConfig")]
        [Validation(Required=false)]
        public UpdateIdentityProviderRequestDingtalkAppConfig DingtalkAppConfig { get; set; }
        public class UpdateIdentityProviderRequestDingtalkAppConfig : TeaModel {
            /// <summary>
            /// <para>AppKey of the DingTalk first-party application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>49nyeaqumk7f</para>
            /// </summary>
            [NameInMap("AppKey")]
            [Validation(Required=false)]
            public string AppKey { get; set; }

            /// <summary>
            /// <para>AppSecret of the DingTalk first-party application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>86nozWFL2CxgwnhKiXaG8dN4keLPkUNc5xxxx</para>
            /// </summary>
            [NameInMap("AppSecret")]
            [Validation(Required=false)]
            public string AppSecret { get; set; }

            /// <summary>
            /// <para>DingTalk QR code login version.</para>
            /// 
            /// <b>Example:</b>
            /// <para>new_version</para>
            /// </summary>
            [NameInMap("DingtalkLoginVersion")]
            [Validation(Required=false)]
            public string DingtalkLoginVersion { get; set; }

            /// <summary>
            /// <para>EncryptKey of the DingTalk application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>VkdWw91mdkrjVFr3ObNwefap21dfxxxx</para>
            /// </summary>
            [NameInMap("EncryptKey")]
            [Validation(Required=false)]
            public string EncryptKey { get; set; }

            /// <summary>
            /// <para>VerificationToken of the DingTalk application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>myDingApp_VerifyTokenxxxxx</para>
            /// </summary>
            [NameInMap("VerificationToken")]
            [Validation(Required=false)]
            public string VerificationToken { get; set; }

        }

        /// <summary>
        /// <para>Identity provider ID.</para>
        /// <para>This parameter is required.</para>
        /// 
        /// <b>Example:</b>
        /// <para>idp_my664lwkhpicbyzirog3xxxxx</para>
        /// </summary>
        [NameInMap("IdentityProviderId")]
        [Validation(Required=false)]
        public string IdentityProviderId { get; set; }

        /// <summary>
        /// <para>Identity provider name.</para>
        /// 
        /// <b>Example:</b>
        /// <para>test</para>
        /// </summary>
        [NameInMap("IdentityProviderName")]
        [Validation(Required=false)]
        public string IdentityProviderName { get; set; }

        /// <summary>
        /// <para>Instance ID.</para>
        /// <para>This parameter is required.</para>
        /// 
        /// <b>Example:</b>
        /// <para>idaas_ue2jvisn35ea5lmthk267xxxxx</para>
        /// </summary>
        [NameInMap("InstanceId")]
        [Validation(Required=false)]
        public string InstanceId { get; set; }

        /// <summary>
        /// <para>Lark configuration information.</para>
        /// </summary>
        [NameInMap("LarkConfig")]
        [Validation(Required=false)]
        public UpdateIdentityProviderRequestLarkConfig LarkConfig { get; set; }
        public class UpdateIdentityProviderRequestLarkConfig : TeaModel {
            /// <summary>
            /// <para>Lark application AppId.</para>
            /// 
            /// <b>Example:</b>
            /// <para>cli_xxxx</para>
            /// </summary>
            [NameInMap("AppId")]
            [Validation(Required=false)]
            public string AppId { get; set; }

            /// <summary>
            /// <para>Lark application AppSecret.</para>
            /// 
            /// <b>Example:</b>
            /// <para>KiiLzh5Dueh4wbLxxxx</para>
            /// </summary>
            [NameInMap("AppSecret")]
            [Validation(Required=false)]
            public string AppSecret { get; set; }

            /// <summary>
            /// <para>EncryptKey of the Lark self-built application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>VkdWw91mdkrjVFr3ObNwefap21dfbZbKxxxx</para>
            /// </summary>
            [NameInMap("EncryptKey")]
            [Validation(Required=false)]
            public string EncryptKey { get; set; }

            /// <summary>
            /// <para>VerificationToken of the Lark self-built application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>feishuVerifyTokenxxxxx</para>
            /// </summary>
            [NameInMap("VerificationToken")]
            [Validation(Required=false)]
            public string VerificationToken { get; set; }

        }

        /// <summary>
        /// <para>AD/LDAP basic information.</para>
        /// </summary>
        [NameInMap("LdapConfig")]
        [Validation(Required=false)]
        public UpdateIdentityProviderRequestLdapConfig LdapConfig { get; set; }
        public class UpdateIdentityProviderRequestLdapConfig : TeaModel {
            /// <summary>
            /// <para>Administrator password.</para>
            /// 
            /// <b>Example:</b>
            /// <para>xxxxxx</para>
            /// </summary>
            [NameInMap("AdministratorPassword")]
            [Validation(Required=false)]
            public string AdministratorPassword { get; set; }

            /// <summary>
            /// <para>Administrator username.</para>
            /// 
            /// <b>Example:</b>
            /// <para>DC=example,DC=com</para>
            /// </summary>
            [NameInMap("AdministratorUsername")]
            [Validation(Required=false)]
            public string AdministratorUsername { get; set; }

            /// <summary>
            /// <para>Whether to verify the fingerprint certificate. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para>Disabled: disabled</para>
            /// </description></item>
            /// <item><description><para>Enabled: enabled</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>enabled</para>
            /// </summary>
            [NameInMap("CertificateFingerprintStatus")]
            [Validation(Required=false)]
            public string CertificateFingerprintStatus { get; set; }

            /// <summary>
            /// <para>Certificate fingerprint list.</para>
            /// </summary>
            [NameInMap("CertificateFingerprints")]
            [Validation(Required=false)]
            public List<string> CertificateFingerprints { get; set; }

            /// <summary>
            /// <para>Communication protocol.</para>
            /// 
            /// <b>Example:</b>
            /// <para>ldap</para>
            /// </summary>
            [NameInMap("LdapProtocol")]
            [Validation(Required=false)]
            public string LdapProtocol { get; set; }

            /// <summary>
            /// <para>Server address.</para>
            /// 
            /// <b>Example:</b>
            /// <para>123.xx.xx.89</para>
            /// </summary>
            [NameInMap("LdapServerHost")]
            [Validation(Required=false)]
            public string LdapServerHost { get; set; }

            /// <summary>
            /// <para>Port number.</para>
            /// 
            /// <b>Example:</b>
            /// <para>636</para>
            /// </summary>
            [NameInMap("LdapServerPort")]
            [Validation(Required=false)]
            public int? LdapServerPort { get; set; }

            /// <summary>
            /// <para>Whether StartTLS is enabled. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para>Disabled: disabled</para>
            /// </description></item>
            /// <item><description><para>Enabled: enabled</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>enabled</para>
            /// </summary>
            [NameInMap("StartTlsStatus")]
            [Validation(Required=false)]
            public string StartTlsStatus { get; set; }

        }

        /// <summary>
        /// <para>Application logo URL.</para>
        /// 
        /// <b>Example:</b>
        /// <para>idaas-image://idaas_23aqr2ye554csg33dqpch5exxxx/tmp/d17d9adc-a943-45e7-ba0c-2838dddea678xxxx</para>
        /// </summary>
        [NameInMap("LogoUrl")]
        [Validation(Required=false)]
        public string LogoUrl { get; set; }

        /// <summary>
        /// <para>Network access endpoint ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>nae_examplexxxx</para>
        /// </summary>
        [NameInMap("NetworkAccessEndpointId")]
        [Validation(Required=false)]
        public string NetworkAccessEndpointId { get; set; }

        /// <summary>
        /// <para>OIDC-related configuration.</para>
        /// </summary>
        [NameInMap("OidcConfig")]
        [Validation(Required=false)]
        public UpdateIdentityProviderRequestOidcConfig OidcConfig { get; set; }
        public class UpdateIdentityProviderRequestOidcConfig : TeaModel {
            /// <summary>
            /// <para>OIDC client authentication configuration.</para>
            /// </summary>
            [NameInMap("AuthnParam")]
            [Validation(Required=false)]
            public UpdateIdentityProviderRequestOidcConfigAuthnParam AuthnParam { get; set; }
            public class UpdateIdentityProviderRequestOidcConfigAuthnParam : TeaModel {
                /// <summary>
                /// <para>OIDC authentication method. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><para>client_secret_basic</para>
                /// </description></item>
                /// <item><description><para>client_secret_post</para>
                /// </description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>client_secret_post</para>
                /// </summary>
                [NameInMap("AuthnMethod")]
                [Validation(Required=false)]
                public string AuthnMethod { get; set; }

                /// <summary>
                /// <para>OIDC client secret.</para>
                /// 
                /// <b>Example:</b>
                /// <para>CSEHDddddddxxxxuxkJEHPveWRXBGqVqRsxxxx</para>
                /// </summary>
                [NameInMap("ClientSecret")]
                [Validation(Required=false)]
                public string ClientSecret { get; set; }

            }

            /// <summary>
            /// <para>OIDC endpoint configuration.</para>
            /// </summary>
            [NameInMap("EndpointConfig")]
            [Validation(Required=false)]
            public UpdateIdentityProviderRequestOidcConfigEndpointConfig EndpointConfig { get; set; }
            public class UpdateIdentityProviderRequestOidcConfigEndpointConfig : TeaModel {
                /// <summary>
                /// <para>OIDC authorization endpoint.</para>
                /// 
                /// <b>Example:</b>
                /// <para><a href="https://example.com/oauth/authorize">https://example.com/oauth/authorize</a></para>
                /// </summary>
                [NameInMap("AuthorizationEndpoint")]
                [Validation(Required=false)]
                public string AuthorizationEndpoint { get; set; }

                /// <summary>
                /// <para>OIDC issuer information.</para>
                /// 
                /// <b>Example:</b>
                /// <para><a href="https://example.com/oauth">https://example.com/oauth</a></para>
                /// </summary>
                [NameInMap("Issuer")]
                [Validation(Required=false)]
                public string Issuer { get; set; }

                /// <summary>
                /// <para>OIDC JWKS URI.</para>
                /// 
                /// <b>Example:</b>
                /// <para><a href="https://example.com/oauth/jwks">https://example.com/oauth/jwks</a></para>
                /// </summary>
                [NameInMap("JwksUri")]
                [Validation(Required=false)]
                public string JwksUri { get; set; }

                /// <summary>
                /// <para>OIDC token endpoint.</para>
                /// 
                /// <b>Example:</b>
                /// <para><a href="https://example.com/oauth/token">https://example.com/oauth/token</a></para>
                /// </summary>
                [NameInMap("TokenEndpoint")]
                [Validation(Required=false)]
                public string TokenEndpoint { get; set; }

                /// <summary>
                /// <para>OIDC UserInfo endpoint.</para>
                /// 
                /// <b>Example:</b>
                /// <para><a href="https://example.com/oauth/userinfo">https://example.com/oauth/userinfo</a></para>
                /// </summary>
                [NameInMap("UserinfoEndpoint")]
                [Validation(Required=false)]
                public string UserinfoEndpoint { get; set; }

            }

            /// <summary>
            /// <para>OIDC grant scopes list.</para>
            /// 
            /// <b>Example:</b>
            /// <para>openid</para>
            /// </summary>
            [NameInMap("GrantScopes")]
            [Validation(Required=false)]
            public List<string> GrantScopes { get; set; }

            /// <summary>
            /// <para>OIDC grant type.</para>
            /// 
            /// <b>Example:</b>
            /// <para>authorization_code</para>
            /// </summary>
            [NameInMap("GrantType")]
            [Validation(Required=false)]
            public string GrantType { get; set; }

            /// <summary>
            /// <para>PKCE algorithm.</para>
            /// <list type="bullet">
            /// <item><description><para>SHA256: S256</para>
            /// </description></item>
            /// <item><description><para>Plain text: plain</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>S256</para>
            /// </summary>
            [NameInMap("PkceChallengeMethod")]
            [Validation(Required=false)]
            public string PkceChallengeMethod { get; set; }

            /// <summary>
            /// <para>Whether to use PKCE in AuthorizationCode grant mode.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("PkceRequired")]
            [Validation(Required=false)]
            public bool? PkceRequired { get; set; }

        }

        [NameInMap("SamlConfig")]
        [Validation(Required=false)]
        public UpdateIdentityProviderRequestSamlConfig SamlConfig { get; set; }
        public class UpdateIdentityProviderRequestSamlConfig : TeaModel {
            /// <summary>
            /// <b>Example:</b>
            /// <para>HTTP-REDIRECT</para>
            /// </summary>
            [NameInMap("BindingMethod")]
            [Validation(Required=false)]
            public string BindingMethod { get; set; }

            [NameInMap("Certificates")]
            [Validation(Required=false)]
            public List<UpdateIdentityProviderRequestSamlConfigCertificates> Certificates { get; set; }
            public class UpdateIdentityProviderRequestSamlConfigCertificates : TeaModel {
                /// <summary>
                /// <b>Example:</b>
                /// <para>-----BEGIN CERTIFICATE----- MIIC0jCCAbqgAwIBAgIQXXXXX-----END CERTIFICATE-----</para>
                /// </summary>
                [NameInMap("Content")]
                [Validation(Required=false)]
                public string Content { get; set; }

            }

            /// <summary>
            /// <b>Example:</b>
            /// <para><a href="http://dc.test.com/adfs/services/trust">http://dc.test.com/adfs/services/trust</a></para>
            /// </summary>
            [NameInMap("IdPEntityId")]
            [Validation(Required=false)]
            public string IdPEntityId { get; set; }

            /// <summary>
            /// <b>Example:</b>
            /// <para><a href="https://dc.test.com/adfs/ls/">https://dc.test.com/adfs/ls/</a></para>
            /// </summary>
            [NameInMap("IdPSsoUrl")]
            [Validation(Required=false)]
            public string IdPSsoUrl { get; set; }

            /// <summary>
            /// <b>Example:</b>
            /// <para>180</para>
            /// </summary>
            [NameInMap("MaxClockSkew")]
            [Validation(Required=false)]
            public long? MaxClockSkew { get; set; }

            /// <summary>
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("RequireRequestSigned")]
            [Validation(Required=false)]
            public bool? RequireRequestSigned { get; set; }

            [NameInMap("WantAssertionsSigned")]
            [Validation(Required=false)]
            public bool? WantAssertionsSigned { get; set; }

            [NameInMap("WantResponseSigned")]
            [Validation(Required=false)]
            public bool? WantResponseSigned { get; set; }

        }

        /// <summary>
        /// <para>WeCom basic information.</para>
        /// </summary>
        [NameInMap("WeComConfig")]
        [Validation(Required=false)]
        public UpdateIdentityProviderRequestWeComConfig WeComConfig { get; set; }
        public class UpdateIdentityProviderRequestWeComConfig : TeaModel {
            /// <summary>
            /// <para>AgentId of the WeCom self-built application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1237403</para>
            /// </summary>
            [NameInMap("AgentId")]
            [Validation(Required=false)]
            public string AgentId { get; set; }

            /// <summary>
            /// <para>Authorization callback domain.</para>
            /// 
            /// <b>Example:</b>
            /// <para><a href="https://xxx.aliyunidaas.com/xxxxx">https://xxx.aliyunidaas.com/xxxxx</a></para>
            /// </summary>
            [NameInMap("AuthorizeCallbackDomain")]
            [Validation(Required=false)]
            public string AuthorizeCallbackDomain { get; set; }

            /// <summary>
            /// <para>CorpSecret of the WeCom self-built application.</para>
            /// 
            /// <b>Example:</b>
            /// <para>CSEHDddddddxxxxuxkJEHPveWRXBGqVqRsxxxx</para>
            /// </summary>
            [NameInMap("CorpSecret")]
            [Validation(Required=false)]
            public string CorpSecret { get; set; }

            /// <summary>
            /// <para>Trusted domain.</para>
            /// 
            /// <b>Example:</b>
            /// <para><a href="https://xxx.aliyunidaas.com">https://xxx.aliyunidaas.com</a></para>
            /// </summary>
            [NameInMap("TrustableDomain")]
            [Validation(Required=false)]
            public string TrustableDomain { get; set; }

        }

    }

}
