// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.CS20151215.Models
{
    public class DescribeTaskInfoResponseBody : TeaModel {
        /// <summary>
        /// <para>The cluster ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>c78592bfe92244365b3c3ad47f1de****</para>
        /// </summary>
        [NameInMap("cluster_id")]
        [Validation(Required=false)]
        public string ClusterId { get; set; }

        /// <summary>
        /// <para>The time when the task was created.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2020-11-10T16:02:04+08:00</para>
        /// </summary>
        [NameInMap("created")]
        [Validation(Required=false)]
        public string Created { get; set; }

        /// <summary>
        /// <para>The current stage of the task.</para>
        /// 
        /// <b>Example:</b>
        /// <para>DrainNodes</para>
        /// </summary>
        [NameInMap("current_stage")]
        [Validation(Required=false)]
        public string CurrentStage { get; set; }

        /// <summary>
        /// <para>The error returned for the task.</para>
        /// </summary>
        [NameInMap("error")]
        [Validation(Required=false)]
        public DescribeTaskInfoResponseBodyError Error { get; set; }
        public class DescribeTaskInfoResponseBodyError : TeaModel {
            /// <summary>
            /// <para>The error code returned.</para>
            /// 
            /// <b>Example:</b>
            /// <para>400</para>
            /// </summary>
            [NameInMap("code")]
            [Validation(Required=false)]
            public string Code { get; set; }

            /// <summary>
            /// <para>The error message returned.</para>
            /// 
            /// <b>Example:</b>
            /// <para>failed to xxx</para>
            /// </summary>
            [NameInMap("message")]
            [Validation(Required=false)]
            public string Message { get; set; }

        }

        /// <summary>
        /// <para>The event generated by the task.</para>
        /// </summary>
        [NameInMap("events")]
        [Validation(Required=false)]
        public List<DescribeTaskInfoResponseBodyEvents> Events { get; set; }
        public class DescribeTaskInfoResponseBodyEvents : TeaModel {
            /// <summary>
            /// <para>The action of the event.</para>
            /// 
            /// <b>Example:</b>
            /// <para>start</para>
            /// </summary>
            [NameInMap("action")]
            [Validation(Required=false)]
            public string Action { get; set; }

            /// <summary>
            /// <para>The severity level of the event.</para>
            /// 
            /// <b>Example:</b>
            /// <para>Normal</para>
            /// </summary>
            [NameInMap("level")]
            [Validation(Required=false)]
            public string Level { get; set; }

            /// <summary>
            /// <para>The message about the event.</para>
            /// 
            /// <b>Example:</b>
            /// <para>start to xxx</para>
            /// </summary>
            [NameInMap("message")]
            [Validation(Required=false)]
            public string Message { get; set; }

            /// <summary>
            /// <para>The cause of the event.</para>
            /// 
            /// <b>Example:</b>
            /// <para>NodePoolUpgradeStart</para>
            /// </summary>
            [NameInMap("reason")]
            [Validation(Required=false)]
            public string Reason { get; set; }

            /// <summary>
            /// <para>The source of the event.</para>
            /// 
            /// <b>Example:</b>
            /// <para>ACK</para>
            /// </summary>
            [NameInMap("source")]
            [Validation(Required=false)]
            public string Source { get; set; }

            /// <summary>
            /// <para>The timestamp when the event was generated.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1669706229286</para>
            /// </summary>
            [NameInMap("timestamp")]
            [Validation(Required=false)]
            public string Timestamp { get; set; }

        }

        /// <summary>
        /// <para>The task parameters.</para>
        /// </summary>
        [NameInMap("parameters")]
        [Validation(Required=false)]
        public Dictionary<string, object> Parameters { get; set; }

        /// <summary>
        /// <para>Detailed information about the stage of the task.</para>
        /// </summary>
        [NameInMap("stages")]
        [Validation(Required=false)]
        public List<DescribeTaskInfoResponseBodyStages> Stages { get; set; }
        public class DescribeTaskInfoResponseBodyStages : TeaModel {
            /// <summary>
            /// <para>The end time of the stage.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2022-12-15 23:00:00</para>
            /// </summary>
            [NameInMap("end_time")]
            [Validation(Required=false)]
            public string EndTime { get; set; }

            /// <summary>
            /// <para>The message about the stage.</para>
            /// 
            /// <b>Example:</b>
            /// <para>success to xxxxx</para>
            /// </summary>
            [NameInMap("message")]
            [Validation(Required=false)]
            public string Message { get; set; }

            /// <summary>
            /// <para>The output generated at the stage.</para>
            /// </summary>
            [NameInMap("outputs")]
            [Validation(Required=false)]
            public Dictionary<string, object> Outputs { get; set; }

            /// <summary>
            /// <para>The start time of the stage.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2022-12-15 23:00:00</para>
            /// </summary>
            [NameInMap("start_time")]
            [Validation(Required=false)]
            public string StartTime { get; set; }

            /// <summary>
            /// <para>The status of the stage.</para>
            /// 
            /// <b>Example:</b>
            /// <para>running</para>
            /// </summary>
            [NameInMap("state")]
            [Validation(Required=false)]
            public string State { get; set; }

        }

        /// <summary>
        /// <para>The status of the task. Valid values:</para>
        /// <list type="bullet">
        /// <item><description><c>running</c>: The task is running.</description></item>
        /// <item><description><c>failed</c>: The task failed.</description></item>
        /// <item><description><c>success</c>: The task is complete.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>running</para>
        /// </summary>
        [NameInMap("state")]
        [Validation(Required=false)]
        public string State { get; set; }

        /// <summary>
        /// <para>The object of the task.</para>
        /// </summary>
        [NameInMap("target")]
        [Validation(Required=false)]
        public DescribeTaskInfoResponseBodyTarget Target { get; set; }
        public class DescribeTaskInfoResponseBodyTarget : TeaModel {
            /// <summary>
            /// <para>The ID of the object.</para>
            /// 
            /// <b>Example:</b>
            /// <para>c78592bfe92244365b3c3ad47f1de****</para>
            /// </summary>
            [NameInMap("id")]
            [Validation(Required=false)]
            public string Id { get; set; }

            /// <summary>
            /// <para>The type of the object.</para>
            /// 
            /// <b>Example:</b>
            /// <para>cluster</para>
            /// </summary>
            [NameInMap("type")]
            [Validation(Required=false)]
            public string Type { get; set; }

        }

        /// <summary>
        /// <para>The task ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>T-5faa48fb31b6b8078d000006</para>
        /// </summary>
        [NameInMap("task_id")]
        [Validation(Required=false)]
        public string TaskId { get; set; }

        /// <summary>
        /// <para>The execution details of the task.</para>
        /// </summary>
        [NameInMap("task_result")]
        [Validation(Required=false)]
        public List<DescribeTaskInfoResponseBodyTaskResult> TaskResult { get; set; }
        public class DescribeTaskInfoResponseBodyTaskResult : TeaModel {
            /// <summary>
            /// <para>The resources that are managed by the task. For a scale-out task, the value of this parameter is the ID of the instance that is added by the task.</para>
            /// 
            /// <b>Example:</b>
            /// <para>i-xxx</para>
            /// </summary>
            [NameInMap("data")]
            [Validation(Required=false)]
            public string Data { get; set; }

            /// <summary>
            /// <para>The status of the scale-out task. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><c>success</c>: The scale-out task is successful.</description></item>
            /// <item><description><c>success</c>: The scale-out task failed.</description></item>
            /// <item><description><c>initial</c>: The scale-out task is being initialized.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>success</para>
            /// </summary>
            [NameInMap("status")]
            [Validation(Required=false)]
            public string Status { get; set; }

        }

        /// <summary>
        /// <para>The task type. A value of <c>cluster_scaleout</c> indicates a scale-out task.</para>
        /// 
        /// <b>Example:</b>
        /// <para>cluster_scaleout</para>
        /// </summary>
        [NameInMap("task_type")]
        [Validation(Required=false)]
        public string TaskType { get; set; }

        /// <summary>
        /// <para>The time when the task was updated.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2020-11-10T16:03:06+08:00</para>
        /// </summary>
        [NameInMap("updated")]
        [Validation(Required=false)]
        public string Updated { get; set; }

    }

}
