// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Qualitycheck20190115.Models
{
    public class OperatorBasicInfo : TeaModel {
        /// <summary>
        /// <para>The primary key ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("Id")]
        [Validation(Required=false)]
        public long? Id { get; set; }

        /// <summary>
        /// <para>The operator name.</para>
        /// 
        /// <b>Example:</b>
        /// <para>a</para>
        /// </summary>
        [NameInMap("Name")]
        [Validation(Required=false)]
        public string Name { get; set; }

        /// <summary>
        /// <para>The ID. This can be the primary key ID or an ID generated by the frontend.</para>
        /// 
        /// <b>Example:</b>
        /// <para>a</para>
        /// </summary>
        [NameInMap("Oid")]
        [Validation(Required=false)]
        public string Oid { get; set; }

        /// <summary>
        /// <para>The operator parameters.</para>
        /// </summary>
        [NameInMap("Param")]
        [Validation(Required=false)]
        public OperatorBasicInfoParam Param { get; set; }
        public class OperatorBasicInfoParam : TeaModel {
            /// <summary>
            /// <para>The threshold for answer hits.</para>
            /// 
            /// <b>Example:</b>
            /// <para>90</para>
            /// </summary>
            [NameInMap("AnswerThreshold")]
            [Validation(Required=false)]
            public string AnswerThreshold { get; set; }

            /// <summary>
            /// <para>The Ant model information.</para>
            /// </summary>
            [NameInMap("AntModelInfo")]
            [Validation(Required=false)]
            public Dictionary<string, string> AntModelInfo { get; set; }

            /// <summary>
            /// <para>For speech rate detection: specifies whether to calculate the average speech rate for the entire dialogue. The default is \<c>false\\</c>.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("Average")]
            [Validation(Required=false)]
            public bool? Average { get; set; }

            /// <summary>
            /// <para>For the duration operator: the start type for the duration calculation. The calculation can start from the beginning of the recording or the beginning of a specific sentence.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("BeginType")]
            [Validation(Required=false)]
            public string BeginType { get; set; }

            /// <summary>
            /// <para>The robot ID.</para>
            /// 
            /// <b>Example:</b>
            /// <para>chatbot-cn-xxx</para>
            /// </summary>
            [NameInMap("BotId")]
            [Validation(Required=false)]
            public string BotId { get; set; }

            /// <summary>
            /// <para>Specifies whether the matching is case-sensitive.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("Case_sensitive")]
            [Validation(Required=false)]
            public bool? CaseSensitive { get; set; }

            /// <summary>
            /// <para>The knowledge category path.</para>
            /// 
            /// <b>Example:</b>
            /// <para>xx</para>
            /// </summary>
            [NameInMap("CategoryPathCode")]
            [Validation(Required=false)]
            public string CategoryPathCode { get; set; }

            /// <summary>
            /// <para>For silence detection: specifies whether to check the first sentence.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("CheckFirstSentence")]
            [Validation(Required=false)]
            public bool? CheckFirstSentence { get; set; }

            /// <summary>
            /// <para>The detection method. The default is 1.</para>
            /// <list type="bullet">
            /// <item><description><para>1: Energy fluctuation between contiguous sentences.</para>
            /// </description></item>
            /// <item><description><para>2: Maximum energy span.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("CheckType")]
            [Validation(Required=false)]
            public int? CheckType { get; set; }

            /// <summary>
            /// <para>The comparison operator. Valid values are \<c>gt\\</c> (greater than) and \<c>lt\\</c> (less than).</para>
            /// 
            /// <b>Example:</b>
            /// <para>gt</para>
            /// </summary>
            [NameInMap("CompareOperator")]
            [Validation(Required=false)]
            public string CompareOperator { get; set; }

            /// <summary>
            /// <para>Specifies whether to match a single sentence.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("ContextChatMatch")]
            [Validation(Required=false)]
            public bool? ContextChatMatch { get; set; }

            /// <summary>
            /// <para>Parameters for the recording-related operator.</para>
            /// </summary>
            [NameInMap("CustomerParam")]
            [Validation(Required=false)]
            public JudgeNodeMetaDesc CustomerParam { get; set; }

            /// <summary>
            /// <para>For the interruption operator: the delay duration.</para>
            /// 
            /// <b>Example:</b>
            /// <para>10</para>
            /// </summary>
            [NameInMap("DelayTime")]
            [Validation(Required=false)]
            public int? DelayTime { get; set; }

            /// <summary>
            /// <para>Used for the time interval operator. If set to \<c>true\\</c>, the target sentence is not included in the calculation if it is spoken by the same role as the current sentence.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("Different_role")]
            [Validation(Required=false)]
            public bool? DifferentRole { get; set; }

            [NameInMap("Dimensions")]
            [Validation(Required=false)]
            public List<OperatorBasicInfoParamDimensions> Dimensions { get; set; }
            public class OperatorBasicInfoParamDimensions : TeaModel {
                [NameInMap("Desc")]
                [Validation(Required=false)]
                public string Desc { get; set; }

                [NameInMap("Dimension")]
                [Validation(Required=false)]
                public string Dimension { get; set; }

                [NameInMap("ExcludeCondition")]
                [Validation(Required=false)]
                public string ExcludeCondition { get; set; }

                [NameInMap("IncludeCondition")]
                [Validation(Required=false)]
                public string IncludeCondition { get; set; }

            }

            /// <summary>
            /// <para>For the duration operator: the end type for the duration calculation. The calculation can end at the end of the recording or the end of a specific sentence.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("EndType")]
            [Validation(Required=false)]
            public string EndType { get; set; }

            /// <summary>
            /// <para>For the contextual repetition operator: the dialogues to exclude.</para>
            /// </summary>
            [NameInMap("Excludes")]
            [Validation(Required=false)]
            public List<string> Excludes { get; set; }

            /// <summary>
            /// <para>For the contextual repetition operator: checks for repetitions within the \<c>from\\</c> number of sentences before the current sentence. A value of \<c>0\\</c> indicates all preceding sentences.</para>
            /// 
            /// <b>Example:</b>
            /// <para>0</para>
            /// </summary>
            [NameInMap("From")]
            [Validation(Required=false)]
            public int? From { get; set; }

            /// <summary>
            /// <para>Used for the time interval operator. Specifies whether to calculate the time interval by subtracting the end time of the target sentence from the end time of the current sentence.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("From_end")]
            [Validation(Required=false)]
            public bool? FromEnd { get; set; }

            [NameInMap("HitCondition")]
            [Validation(Required=false)]
            public string HitCondition { get; set; }

            /// <summary>
            /// <para>For the contextual repetition operator: the number of repetitions.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("Hit_time")]
            [Validation(Required=false)]
            public int? HitTime { get; set; }

            /// <summary>
            /// <para>The effective sentences. \<c>true\\</c> indicates a single sentence. \<c>false\\</c> indicates multiple sentences.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("In_sentence")]
            [Validation(Required=false)]
            public bool? InSentence { get; set; }

            /// <summary>
            /// <para>The start of the interval.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("Interval")]
            [Validation(Required=false)]
            public int? Interval { get; set; }

            /// <summary>
            /// <para>The end of the interval.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("IntervalEnd")]
            [Validation(Required=false)]
            public int? IntervalEnd { get; set; }

            /// <summary>
            /// <para>The keyword extension.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("KeywordExtension")]
            [Validation(Required=false)]
            public int? KeywordExtension { get; set; }

            /// <summary>
            /// <para>The number of matched keywords.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("KeywordMatchSize")]
            [Validation(Required=false)]
            public int? KeywordMatchSize { get; set; }

            /// <summary>
            /// <para>The keywords.</para>
            /// </summary>
            [NameInMap("Keywords")]
            [Validation(Required=false)]
            public List<string> Keywords { get; set; }

            /// <summary>
            /// <para>The knowledge information.</para>
            /// 
            /// <b>Example:</b>
            /// <para>下单</para>
            /// </summary>
            [NameInMap("KnowledgeInfo")]
            [Validation(Required=false)]
            public string KnowledgeInfo { get; set; }

            /// <summary>
            /// <para>The number of sentences after a question is hit within which to detect the answer.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("KnowledgeSentenceNum")]
            [Validation(Required=false)]
            public int? KnowledgeSentenceNum { get; set; }

            /// <summary>
            /// <para>The knowledge category or knowledge ID.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("KnowledgeTargetId")]
            [Validation(Required=false)]
            public string KnowledgeTargetId { get; set; }

            /// <summary>
            /// <para>The name of the knowledge category or knowledge.</para>
            /// 
            /// <b>Example:</b>
            /// <para>订单</para>
            /// </summary>
            [NameInMap("KnowledgeTargetName")]
            [Validation(Required=false)]
            public string KnowledgeTargetName { get; set; }

            /// <summary>
            /// <para>0: Category. 1: Knowledge.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("KnowledgeTargetType")]
            [Validation(Required=false)]
            public int? KnowledgeTargetType { get; set; }

            [NameInMap("Knowledges")]
            [Validation(Required=false)]
            public string Knowledges { get; set; }

            /// <summary>
            /// <para>The LGF sentences.</para>
            /// </summary>
            [NameInMap("LgfSentences")]
            [Validation(Required=false)]
            public List<string> LgfSentences { get; set; }

            [NameInMap("LlmModelCode")]
            [Validation(Required=false)]
            public string LlmModelCode { get; set; }

            /// <summary>
            /// <para>The change in energy value. The default is 3. The range is 1 to 9.</para>
            /// 
            /// <b>Example:</b>
            /// <para>3</para>
            /// </summary>
            [NameInMap("MaxEmotionChangeValue")]
            [Validation(Required=false)]
            public int? MaxEmotionChangeValue { get; set; }

            /// <summary>
            /// <para>The minimum number of words in a sentence. Sentences with fewer words than this value are not checked.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("MinWordSize")]
            [Validation(Required=false)]
            public int? MinWordSize { get; set; }

            /// <summary>
            /// <para>\<c>true\\</c> indicates that the two contiguous sentences from different roles are used. \<c>false\\</c> indicates that the first sentence from each role is used to compare the response time. The default is \<c>false\\</c>.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("Near_dialogue")]
            [Validation(Required=false)]
            public bool? NearDialogue { get; set; }

            /// <summary>
            /// <para>The regular expression to exclude.</para>
            /// 
            /// <b>Example:</b>
            /// <para>优秀.*</para>
            /// </summary>
            [NameInMap("NotRegex")]
            [Validation(Required=false)]
            public string NotRegex { get; set; }

            /// <summary>
            /// <para>The statement.</para>
            /// 
            /// <b>Example:</b>
            /// <para>你好，请问</para>
            /// </summary>
            [NameInMap("Phrase")]
            [Validation(Required=false)]
            public string Phrase { get; set; }

            /// <summary>
            /// <para>The variable required for foreign-related properties.</para>
            /// 
            /// <b>Example:</b>
            /// <para>xx</para>
            /// </summary>
            [NameInMap("Pkey")]
            [Validation(Required=false)]
            public string Pkey { get; set; }

            /// <summary>
            /// <para>The poutput type.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("Poutput_type")]
            [Validation(Required=false)]
            public int? PoutputType { get; set; }

            /// <summary>
            /// <para>The model detection type.</para>
            /// </summary>
            [NameInMap("Pvalues")]
            [Validation(Required=false)]
            public List<string> Pvalues { get; set; }

            /// <summary>
            /// <para>The threshold for question hits.</para>
            /// 
            /// <b>Example:</b>
            /// <para>90</para>
            /// </summary>
            [NameInMap("QuestionThreshold")]
            [Validation(Required=false)]
            public string QuestionThreshold { get; set; }

            /// <summary>
            /// <para>The references.</para>
            /// </summary>
            [NameInMap("References")]
            [Validation(Required=false)]
            public List<string> References { get; set; }

            /// <summary>
            /// <para>The regular expression.</para>
            /// 
            /// <b>Example:</b>
            /// <para>质疑.*</para>
            /// </summary>
            [NameInMap("Regex")]
            [Validation(Required=false)]
            public string Regex { get; set; }

            /// <summary>
            /// <para>The role used in the operator. This parameter is currently used for the contextual repetition operator in conjunction with \<c>Target_role\\</c>.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("RoleId")]
            [Validation(Required=false)]
            public int? RoleId { get; set; }

            [NameInMap("SceneName")]
            [Validation(Required=false)]
            public string SceneName { get; set; }

            /// <summary>
            /// <para>The score.</para>
            /// 
            /// <b>Example:</b>
            /// <para>70</para>
            /// </summary>
            [NameInMap("Score")]
            [Validation(Required=false)]
            public int? Score { get; set; }

            /// <summary>
            /// <para>The similarity threshold.</para>
            /// 
            /// <b>Example:</b>
            /// <para>90</para>
            /// </summary>
            [NameInMap("Similarity_threshold")]
            [Validation(Required=false)]
            public double? SimilarityThreshold { get; set; }

            /// <summary>
            /// <para>Similar questions.</para>
            /// </summary>
            [NameInMap("SimilarlySentences")]
            [Validation(Required=false)]
            public List<string> SimilarlySentences { get; set; }

            /// <summary>
            /// <para>The synonyms.</para>
            /// </summary>
            [NameInMap("Synonyms")]
            [Validation(Required=false)]
            public Dictionary<string, List<string>> Synonyms { get; set; }

            /// <summary>
            /// <para>The target sentence, specified as the number of sentences before the current one. If set to 0, the time interval is calculated as the end time of the current sentence minus its start time.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("Target")]
            [Validation(Required=false)]
            public int? Target { get; set; }

            /// <summary>
            /// <para>Used for the repetition operator. If the current sentence matches the regular expression, the matched part is searched for in the sentences spoken by the specified \<c>Target_role\\</c> that appear before the current sentence.</para>
            /// 
            /// <b>Example:</b>
            /// <para>客服</para>
            /// </summary>
            [NameInMap("Target_role")]
            [Validation(Required=false)]
            public string TargetRole { get; set; }

            /// <summary>
            /// <para>The threshold.</para>
            /// 
            /// <b>Example:</b>
            /// <para>90</para>
            /// </summary>
            [NameInMap("Threshold")]
            [Validation(Required=false)]
            public float? Threshold { get; set; }

            /// <summary>
            /// <para>Specifies whether to use the EAS algorithm.</para>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("UseEasAlgorithm")]
            [Validation(Required=false)]
            public bool? UseEasAlgorithm { get; set; }

            /// <summary>
            /// <para>Used for the speech rate operator. The speech rate value per unit of time. It determines whether the speech rate of the current sentence exceeds the specified value. The time unit depends on the time units of the \<c>start\\</c> and \<c>end\\</c> parameters.</para>
            /// 
            /// <b>Example:</b>
            /// <para>111</para>
            /// </summary>
            [NameInMap("Velocity")]
            [Validation(Required=false)]
            public double? Velocity { get; set; }

            /// <summary>
            /// <para>Used for the speech rate operator. The speech rate value per minute. It determines whether the speech rate of the current sentence exceeds the specified value.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("VelocityInMint")]
            [Validation(Required=false)]
            public int? VelocityInMint { get; set; }

        }

        /// <summary>
        /// <para>The quality check type:</para>
        /// <list type="bullet">
        /// <item><description><para>0: Offline check</para>
        /// </description></item>
        /// <item><description><para>1: Real-time check</para>
        /// </description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>0</para>
        /// </summary>
        [NameInMap("QualityCheckType")]
        [Validation(Required=false)]
        public int? QualityCheckType { get; set; }

        /// <summary>
        /// <para>The operator category.</para>
        /// 
        /// <b>Example:</b>
        /// <para>HIT_ANY_KEYWORDS</para>
        /// </summary>
        [NameInMap("Type")]
        [Validation(Required=false)]
        public string Type { get; set; }

        /// <summary>
        /// <para>The user group.</para>
        /// 
        /// <b>Example:</b>
        /// <para>xxx</para>
        /// </summary>
        [NameInMap("UserGroup")]
        [Validation(Required=false)]
        public string UserGroup { get; set; }

    }

}
