// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.PaiLLMTrace20240311.Models
{
    public class UpdateOnlineEvalTaskRequest : TeaModel {
        /// <summary>
        /// <para>The user-defined name of the LLM application.</para>
        /// 
        /// <b>Example:</b>
        /// <para>my-llm-one</para>
        /// </summary>
        [NameInMap("AppName")]
        [Validation(Required=false)]
        public string AppName { get; set; }

        /// <summary>
        /// <para>The description of the task.</para>
        /// 
        /// <b>Example:</b>
        /// <para>The purpose of the task is xxx.</para>
        /// </summary>
        [NameInMap("Description")]
        [Validation(Required=false)]
        public string Description { get; set; }

        /// <summary>
        /// <para>The end time of the trace data, in UTC format.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2024-09-02 22:24:00</para>
        /// </summary>
        [NameInMap("EndTime")]
        [Validation(Required=false)]
        public string EndTime { get; set; }

        /// <summary>
        /// <para>This configuration structure defines the JSON paths needed to extract specific values from trace data in JSON format. EvaluationConfig defines these JSON paths.</para>
        /// </summary>
        [NameInMap("EvaluationConfig")]
        [Validation(Required=false)]
        public EvaluationConfig EvaluationConfig { get; set; }

        /// <summary>
        /// <para>The evaluation task must search for a certain amount of trace data generated by the user application as input data for the evaluation. This list defines the search filter conditions.</para>
        /// </summary>
        [NameInMap("Filters")]
        [Validation(Required=false)]
        public List<UpdateOnlineEvalTaskRequestFilters> Filters { get; set; }
        public class UpdateOnlineEvalTaskRequestFilters : TeaModel {
            /// <summary>
            /// <para>The key of the filter condition.</para>
            /// <para>Valid values:</para>
            /// <list type="bullet">
            /// <item><description>Status</description></item>
            /// <item><description>SpanName</description></item>
            /// <item><description>Input</description></item>
            /// <item><description>TraceType</description></item>
            /// <item><description>SpanType</description></item>
            /// <item><description>ServiceName</description></item>
            /// <item><description>Output</description></item>
            /// <item><description>TraceName</description></item>
            /// <item><description>ServiceId</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>ServiceId
            /// ServiceName
            /// Input
            /// Output
            /// Status
            /// TraceType
            /// SpanType
            /// TraceName
            /// SpanName</para>
            /// </summary>
            [NameInMap("Key")]
            [Validation(Required=false)]
            public string Key { get; set; }

            /// <summary>
            /// <para>The matching operator of the filter condition.</para>
            /// <para>Valid values:</para>
            /// <list type="bullet">
            /// <item><description>Contains</description></item>
            /// <item><description>\=</description></item>
            /// <item><description>StartsWith</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>=
            /// StartsWith
            /// Contains</para>
            /// </summary>
            [NameInMap("Operator")]
            [Validation(Required=false)]
            public string Operator { get; set; }

            /// <summary>
            /// <para>The value of the filter condition.</para>
            /// 
            /// <b>Example:</b>
            /// <para>foo</para>
            /// </summary>
            [NameInMap("Value")]
            [Validation(Required=false)]
            public string Value { get; set; }

        }

        /// <summary>
        /// <para>The access configuration structure of the model used in the evaluation.</para>
        /// </summary>
        [NameInMap("ModelConfig")]
        [Validation(Required=false)]
        public ModelConfig ModelConfig { get; set; }

        /// <summary>
        /// <para>The evaluation task must search for a certain amount of trace data generated by the user application as input data for the evaluation. This is the width of the time window for each search of input data.</para>
        /// 
        /// <b>Example:</b>
        /// <para>10</para>
        /// </summary>
        [NameInMap("SamplingFrequencyMinutes")]
        [Validation(Required=false)]
        public int? SamplingFrequencyMinutes { get; set; }

        /// <summary>
        /// <para>The percentage of data found in a time window that truly serves as evaluation input data. For example, 100 indicates that all data searched is used as evaluation input. 20 indicates that 20% of the found data is randomly selected as evaluation input.</para>
        /// 
        /// <b>Example:</b>
        /// <para>50</para>
        /// </summary>
        [NameInMap("SamplingRatio")]
        [Validation(Required=false)]
        public int? SamplingRatio { get; set; }

        /// <summary>
        /// <para>The start time of the trace data, in UTC format.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2024-07-31 08:30:00</para>
        /// </summary>
        [NameInMap("StartTime")]
        [Validation(Required=false)]
        public string StartTime { get; set; }

        /// <summary>
        /// <para>The task name.</para>
        /// 
        /// <b>Example:</b>
        /// <para>foo model application performance evaluation</para>
        /// </summary>
        [NameInMap("TaskName")]
        [Validation(Required=false)]
        public string TaskName { get; set; }

    }

}
