// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Cloudsso20210515.Models
{
    public class ResetUserPasswordRequest : TeaModel {
        /// <summary>
        /// <para>The ID of the directory.</para>
        /// 
        /// <b>Example:</b>
        /// <para>d-00fc2p61****</para>
        /// </summary>
        [NameInMap("DirectoryId")]
        [Validation(Required=false)]
        public string DirectoryId { get; set; }

        /// <summary>
        /// <para>Specifies whether to enable the system to automatically generate a new password. Valid values:</para>
        /// <list type="bullet">
        /// <item><description>True: The new password is automatically generated by the system.</description></item>
        /// <item><description>False: The new password must be manually specified. This is the default value.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>True</para>
        /// </summary>
        [NameInMap("GenerateRandomPassword")]
        [Validation(Required=false)]
        public bool? GenerateRandomPassword { get; set; }

        /// <summary>
        /// <para>The new password.</para>
        /// <para>The password must contain the following types of characters: uppercase letters, lowercase letters, digits, and special characters.</para>
        /// <para>The password must be 8 to 32 characters in length.</para>
        /// <remarks>
        /// <para> If you set <c>GenerateRandomPassword</c> to <c>False</c>, you must specify <c>Password</c> .</para>
        /// </remarks>
        /// 
        /// <b>Example:</b>
        /// <para>uc)XK$?ictf72CKFDy9vtWaFmISl****</para>
        /// </summary>
        [NameInMap("Password")]
        [Validation(Required=false)]
        public string Password { get; set; }

        /// <summary>
        /// <para>Specifies whether password reset is required upon the next logon. Valid values:</para>
        /// <list type="bullet">
        /// <item><description>True: Password reset is required upon the next logon.</description></item>
        /// <item><description>False: Password reset is not required upon the next logon. This is the default value.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>False</para>
        /// </summary>
        [NameInMap("RequirePasswordResetForNextLogin")]
        [Validation(Required=false)]
        public bool? RequirePasswordResetForNextLogin { get; set; }

        /// <summary>
        /// <para>The ID of the user.</para>
        /// 
        /// <b>Example:</b>
        /// <para>u-00q8wbq42wiltcrk****</para>
        /// </summary>
        [NameInMap("UserId")]
        [Validation(Required=false)]
        public string UserId { get; set; }

    }

}
