// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Cloudsso20210515.Models
{
    public class ResetUserPasswordResponseBody : TeaModel {
        /// <summary>
        /// <para>The new password.</para>
        /// <remarks>
        /// <para> This parameter is returned only when the new password is automatically generated by the system.</para>
        /// </remarks>
        /// 
        /// <b>Example:</b>
        /// <para>W2koInFIm0Wy2wVZ$oB)MzD$nY!G****</para>
        /// </summary>
        [NameInMap("NewPassword")]
        [Validation(Required=false)]
        public string NewPassword { get; set; }

        /// <summary>
        /// <para>The ID of the request.</para>
        /// 
        /// <b>Example:</b>
        /// <para>F44F02EC-70D1-5E51-8E8E-FA9AC4EF952A</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
