// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Yundun_bastionhost20191209.Models
{
    public class AddUsersToGroupResponseBody : TeaModel {
        /// <summary>
        /// <para>The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use it to troubleshoot issues.</para>
        /// 
        /// <b>Example:</b>
        /// <para>EC9BF0F4-8983-491A-BC8C-1B4DD94976DE</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>The result information of the operation.</para>
        /// </summary>
        [NameInMap("Results")]
        [Validation(Required=false)]
        public List<AddUsersToGroupResponseBodyResults> Results { get; set; }
        public class AddUsersToGroupResponseBodyResults : TeaModel {
            /// <summary>
            /// <para>The result of the operation. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>OK</b>: The operation was successful.</para>
            /// </description></item>
            /// <item><description><para><b>UNEXPECTED</b>: An unknown error occurred.</para>
            /// </description></item>
            /// <item><description><para><b>INVALID_ARGUMENT</b>: The request parameters are invalid.</para>
            /// <remarks>
            /// <para>Check the request parameters and call the operation again.</para>
            /// </remarks>
            /// </description></item>
            /// <item><description><para><b>OBJECT_NOT_FOUND</b>: The specified object does not exist.</para>
            /// <remarks>
            /// <para>Check whether the bastion host instance ID exists, whether the host exists, and whether the host ID is correct, and then call the operation again.</para>
            /// </remarks>
            /// </description></item>
            /// <item><description><para><b>OBJECT_AlREADY_EXISTS</b>: The specified object already exists.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>OK</para>
            /// </summary>
            [NameInMap("Code")]
            [Validation(Required=false)]
            public string Code { get; set; }

            /// <summary>
            /// <para>This parameter is deprecated and can be ignored.</para>
            /// 
            /// <b>Example:</b>
            /// <para>None</para>
            /// </summary>
            [NameInMap("Message")]
            [Validation(Required=false)]
            public string Message { get; set; }

            /// <summary>
            /// <para>The user group ID.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("UserGroupId")]
            [Validation(Required=false)]
            public string UserGroupId { get; set; }

            /// <summary>
            /// <para>The user ID.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("UserId")]
            [Validation(Required=false)]
            public string UserId { get; set; }

        }

    }

}
