// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Dypnsapi20170525.Models
{
    public class SendSmsVerifyCodeRequest : TeaModel {
        /// <summary>
        /// The length of the verification code. Default value: 4. Valid values: 4 to 8.
        /// </summary>
        [NameInMap("CodeLength")]
        [Validation(Required=false)]
        public long? CodeLength { get; set; }

        /// <summary>
        /// The type of the generated verification code. Default value: 1. Valid values:
        /// 
        /// *   1: digits only
        /// *   2: uppercase letters only
        /// *   3: lowercase letters only
        /// *   4: uppercase and lowercase letters
        /// *   5: digits and uppercase letters
        /// *   6: digits and lowercase letters
        /// *   7: digits and uppercase and lowercase letters
        /// </summary>
        [NameInMap("CodeType")]
        [Validation(Required=false)]
        public long? CodeType { get; set; }

        /// <summary>
        /// The country code of the phone number. SMS verification codes can be sent only by using phone numbers in the Chinese mainland. Default value: 86.
        /// </summary>
        [NameInMap("CountryCode")]
        [Validation(Required=false)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Specifies how to handle the verification codes received earlier in a case where verification codes are sent to the same phone number for the same scenario within the validity period.
        /// 
        /// *   1 (default): The latest verification code overwrites the verification codes received earlier. In this case, verification codes received earlier expire.
        /// *   2: Verification codes within their validity period are valid and can be used for verification.
        /// </summary>
        [NameInMap("DuplicatePolicy")]
        [Validation(Required=false)]
        public long? DuplicatePolicy { get; set; }

        /// <summary>
        /// The time interval. Unit: seconds. Default value: 60. This parameter specifies how often you can send a verification code.
        /// </summary>
        [NameInMap("Interval")]
        [Validation(Required=false)]
        public long? Interval { get; set; }

        /// <summary>
        /// The external ID.
        /// </summary>
        [NameInMap("OutId")]
        [Validation(Required=false)]
        public string OutId { get; set; }

        [NameInMap("OwnerId")]
        [Validation(Required=false)]
        public long? OwnerId { get; set; }

        /// <summary>
        /// The phone number.
        /// </summary>
        [NameInMap("PhoneNumber")]
        [Validation(Required=false)]
        public string PhoneNumber { get; set; }

        [NameInMap("ResourceOwnerAccount")]
        [Validation(Required=false)]
        public string ResourceOwnerAccount { get; set; }

        [NameInMap("ResourceOwnerId")]
        [Validation(Required=false)]
        public long? ResourceOwnerId { get; set; }

        /// <summary>
        /// Specifies whether to return a verification code.
        /// 
        /// *   **true**
        /// *   **false**
        /// </summary>
        [NameInMap("ReturnVerifyCode")]
        [Validation(Required=false)]
        public bool? ReturnVerifyCode { get; set; }

        /// <summary>
        /// The verification service name. If this parameter is not specified, the default service is used. The name can be up to 20 characters in length.
        /// </summary>
        [NameInMap("SchemeName")]
        [Validation(Required=false)]
        public string SchemeName { get; set; }

        /// <summary>
        /// The signature.
        /// </summary>
        [NameInMap("SignName")]
        [Validation(Required=false)]
        public string SignName { get; set; }

        /// <summary>
        /// The extension code of the upstream text message. Upstream text messages are text messages sent to the communication service provider. Upstream text messages are used to customize a service, complete an inquiry, or send a request. You are charged for sending upstream text messages based on the billing standards of the service provider.
        /// 
        /// >  The extension code is automatically generated by the system when the signature is generated. You do not need to specify the extension code. You can skip this parameter based on your business requirements. If you want to use custom extension codes, contact your account manager.
        /// </summary>
        [NameInMap("SmsUpExtendCode")]
        [Validation(Required=false)]
        public string SmsUpExtendCode { get; set; }

        /// <summary>
        /// The code of the text message template.
        /// 
        /// Log on to the [SMS console](https://dysms.console.aliyun.com/dysms.htm?spm=5176.12818093.categories-n-products.ddysms.3b2816d0xml2NA#/overview). In the left-side navigation pane, click **Go China** or **Go Globe**. You can view the text message template code in the **Template Code** column on the **Message Templates** tab.
        /// 
        /// >  The text message templates must be created on the Go Globe page and approved.
        /// </summary>
        [NameInMap("TemplateCode")]
        [Validation(Required=false)]
        public string TemplateCode { get; set; }

        /// <summary>
        /// The value of the variable in the text message template. The verification code is replaced with "##code##".
        /// 
        /// Example 1: For a system-defined template that contains variables, if the template content is "Your verification code is ${code} and valid for 5 minutes. Do not disclose the verification code to others.", specify the value of this parameter as {"code":"##code##"}
        /// 
        /// Example 2: For a custom template, if the template content is ${content}, specify the value of this parameter as {"content":"Your verification code is ##code## and must be used within 5 minutes."}.
        /// 
        /// > 
        /// 
        /// *   If line breaks are required in JSON-formatted data, they must meet the relevant requirements that are specified in the standard JSON protocol.
        /// 
        /// *   For more information about template variables, see [SMS template specifications](~~108253~~).
        /// </summary>
        [NameInMap("TemplateParam")]
        [Validation(Required=false)]
        public string TemplateParam { get; set; }

        /// <summary>
        /// The validity period of the verification code. Unit: seconds. Default value: 300.
        /// </summary>
        [NameInMap("ValidTime")]
        [Validation(Required=false)]
        public long? ValidTime { get; set; }

    }

}
