// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.DlfNext20250310.Models
{
    public class CreateCatalogResponseBody : TeaModel {
        /// <summary>
        /// <para>The data catalog ID, which is the primary key of the resource. This value is generated by the server.</para>
        /// 
        /// <b>Example:</b>
        /// <para>clg-paimon-xxx</para>
        /// </summary>
        [NameInMap("catalogId")]
        [Validation(Required=false)]
        public string CatalogId { get; set; }

    }

}
