// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Cms20240330.Models
{
    public class NotifyPolicyConfig : TeaModel {
        /// <summary>
        /// <para>The description of the policy, which helps identify its purpose.</para>
        /// 
        /// <b>Example:</b>
        /// <para>生产环境告警通知策略</para>
        /// </summary>
        [NameInMap("description")]
        [Validation(Required=false)]
        public string Description { get; set; }

        /// <summary>
        /// <para>The policy name. We recommend that you specify this parameter for the Create operation. If a policy with the same name already exists in the workspace, ConflictName (409) is returned.</para>
        /// 
        /// <b>Example:</b>
        /// <para>生产环境告警通知策略</para>
        /// </summary>
        [NameInMap("name")]
        [Validation(Required=false)]
        public string Name { get; set; }

        /// <summary>
        /// <para>The notification strategy sub-entity, which includes noise reduction, notification routing, channels, and custom templates. Required for the Create operation.</para>
        /// 
        /// <b>Example:</b>
        /// <para>{}</para>
        /// </summary>
        [NameInMap("notifyStrategy")]
        [Validation(Required=false)]
        public NotifyStrategyConfig NotifyStrategy { get; set; }

        /// <summary>
        /// <para>The response plan sub-entity, which includes upgrade, repeated notification, automatic recovery, and action integration. Optional.</para>
        /// 
        /// <b>Example:</b>
        /// <para>{}</para>
        /// </summary>
        [NameInMap("responsePlan")]
        [Validation(Required=false)]
        public ResponsePlanConfig ResponsePlan { get; set; }

        /// <summary>
        /// <para>The subscription sub-entity, which includes event filtering, cross-workspace routing, and legacy product event subscription switches. Optional. If not specified, all events in the current workspace are subscribed to.</para>
        /// 
        /// <b>Example:</b>
        /// <para>{}</para>
        /// </summary>
        [NameInMap("subscription")]
        [Validation(Required=false)]
        public SubscriptionConfig Subscription { get; set; }

        /// <summary>
        /// <para>The unique identifier of the policy. Required for the Update operation. Omitted for the Create operation because it is generated by the backend.</para>
        /// 
        /// <b>Example:</b>
        /// <para>04779a183add4f2ca06ab440f16cc580</para>
        /// </summary>
        [NameInMap("uuid")]
        [Validation(Required=false)]
        public string Uuid { get; set; }

        /// <summary>
        /// <para>Required for the Update operation. The write succeeds only when this value matches the backend record. If the values do not match, OptimisticLockFailed is returned.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("version")]
        [Validation(Required=false)]
        public int? Version { get; set; }

    }

}
