// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.FC_Open20210406.Models
{
    public class ListServicesResponseBody : TeaModel {
        /// <summary>
        /// The token used to obtain more results. If this parameter is left empty, all the results are returned.
        /// </summary>
        [NameInMap("nextToken")]
        [Validation(Required=false)]
        public string NextToken { get; set; }

        /// <summary>
        /// The information about a service.
        /// </summary>
        [NameInMap("services")]
        [Validation(Required=false)]
        public List<ListServicesResponseBodyServices> Services { get; set; }
        public class ListServicesResponseBodyServices : TeaModel {
            /// <summary>
            /// The time when the service was created.
            /// </summary>
            [NameInMap("createdTime")]
            [Validation(Required=false)]
            public string CreatedTime { get; set; }

            /// <summary>
            /// The description of the service.
            /// </summary>
            [NameInMap("description")]
            [Validation(Required=false)]
            public string Description { get; set; }

            /// <summary>
            /// Specifies whether to allow functions to access the Internet. Valid values:
            /// 
            /// *   **true**: allows functions in the specified service to access the Internet.
            /// *   **false**: does not allow functions to access the Internet.
            /// </summary>
            [NameInMap("internetAccess")]
            [Validation(Required=false)]
            public bool? InternetAccess { get; set; }

            /// <summary>
            /// The time when the service was last modified.
            /// </summary>
            [NameInMap("lastModifiedTime")]
            [Validation(Required=false)]
            public string LastModifiedTime { get; set; }

            /// <summary>
            /// The log configuration, which specifies a Logstore to store function execution logs.
            /// </summary>
            [NameInMap("logConfig")]
            [Validation(Required=false)]
            public LogConfig LogConfig { get; set; }

            /// <summary>
            /// The configurations of the NAS file system. The configuration allows functions in the specified service in Function Compute to access the NAS file system.
            /// </summary>
            [NameInMap("nasConfig")]
            [Validation(Required=false)]
            public NASConfig NasConfig { get; set; }

            /// <summary>
            /// The OSS mount configurations.
            /// </summary>
            [NameInMap("ossMountConfig")]
            [Validation(Required=false)]
            public OSSMountConfig OssMountConfig { get; set; }

            /// <summary>
            /// The RAM role that is used to grant required permissions to Function Compute. The RAM role is used in the following scenarios:
            /// 
            /// *   Sends function execution logs to your Logstore.
            /// *   Generates a token for a function to access other cloud resources during function execution.
            /// </summary>
            [NameInMap("role")]
            [Validation(Required=false)]
            public string Role { get; set; }

            /// <summary>
            /// The unique ID generated by the system for the service.
            /// </summary>
            [NameInMap("serviceId")]
            [Validation(Required=false)]
            public string ServiceId { get; set; }

            /// <summary>
            /// The name of the service.
            /// </summary>
            [NameInMap("serviceName")]
            [Validation(Required=false)]
            public string ServiceName { get; set; }

            /// <summary>
            /// The configuration of Tracing Analysis. After you configure Tracing Analysis for a service in Function Compute, you can record the execution duration of a request, view the amount of cold start time for a function, and record the execution duration of a function. For more information, see [Overview](~~189804~~).
            /// </summary>
            [NameInMap("tracingConfig")]
            [Validation(Required=false)]
            public TracingConfig TracingConfig { get; set; }

            [NameInMap("useSLRAuthentication")]
            [Validation(Required=false)]
            public bool? UseSLRAuthentication { get; set; }

            /// <summary>
            /// The VPC configuration. The configuration allows a function to access the specified VPC.
            /// </summary>
            [NameInMap("vpcConfig")]
            [Validation(Required=false)]
            public VPCConfig VpcConfig { get; set; }

        }

    }

}
