// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Rds20140815.Models
{
    public class DescribeBackupTasksResponseBody : TeaModel {
        /// <summary>
        /// <para>The backup tasks.</para>
        /// </summary>
        [NameInMap("Items")]
        [Validation(Required=false)]
        public DescribeBackupTasksResponseBodyItems Items { get; set; }
        public class DescribeBackupTasksResponseBodyItems : TeaModel {
            [NameInMap("BackupJob")]
            [Validation(Required=false)]
            public List<DescribeBackupTasksResponseBodyItemsBackupJob> BackupJob { get; set; }
            public class DescribeBackupTasksResponseBodyItemsBackupJob : TeaModel {
                /// <summary>
                /// <para>The ID of the backup set that is generated by the backup task.</para>
                /// <remarks>
                /// <para> If the value of the <b>BackupStatus</b> parameter is <b>Finished</b>, you can view the backup set ID only if you configure the <b>BackupJobId</b> parameter.</para>
                /// </remarks>
                /// 
                /// <b>Example:</b>
                /// <para>346650271</para>
                /// </summary>
                [NameInMap("BackupId")]
                [Validation(Required=false)]
                public string BackupId { get; set; }

                /// <summary>
                /// <para>The ID of the backup task.</para>
                /// 
                /// <b>Example:</b>
                /// <para>4762614</para>
                /// </summary>
                [NameInMap("BackupJobId")]
                [Validation(Required=false)]
                public string BackupJobId { get; set; }

                /// <summary>
                /// <para>The status of the backup program. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><b>NoStart</b></description></item>
                /// <item><description><b>Preparing</b></description></item>
                /// <item><description><b>Waiting</b></description></item>
                /// <item><description><b>Uploading</b></description></item>
                /// <item><description><b>Checking</b></description></item>
                /// <item><description><b>Finished</b></description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>NoStart</para>
                /// </summary>
                [NameInMap("BackupProgressStatus")]
                [Validation(Required=false)]
                public string BackupProgressStatus { get; set; }

                /// <summary>
                /// <para>The status of the backup task. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><b>NoStart</b></description></item>
                /// <item><description><b>Checking</b></description></item>
                /// <item><description><b>Preparing</b></description></item>
                /// <item><description><b>Waiting</b></description></item>
                /// <item><description><b>Uploading</b></description></item>
                /// <item><description><b>Finished</b></description></item>
                /// <item><description><b>Failed</b></description></item>
                /// </list>
                /// <remarks>
                /// <para> This parameter is returned only after a backup task is run.</para>
                /// </remarks>
                /// 
                /// <b>Example:</b>
                /// <para>NoStart</para>
                /// </summary>
                [NameInMap("BackupStatus")]
                [Validation(Required=false)]
                public string BackupStatus { get; set; }

                /// <summary>
                /// <para>The backup mode. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><b>Automated</b></description></item>
                /// <item><description><b>Manual</b></description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>Automated</para>
                /// </summary>
                [NameInMap("JobMode")]
                [Validation(Required=false)]
                public string JobMode { get; set; }

                /// <summary>
                /// <para>The progress of the task in percentage.</para>
                /// 
                /// <b>Example:</b>
                /// <para>25</para>
                /// </summary>
                [NameInMap("Process")]
                [Validation(Required=false)]
                public string Process { get; set; }

                /// <summary>
                /// <para>The type of the task. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><b>TempBackupTask</b>: The backup task is an adhoc backup task.</description></item>
                /// <item><description><b>NormalBackupTask</b>: The backup task is a common backup task.</description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>NormalBackupTask</para>
                /// </summary>
                [NameInMap("TaskAction")]
                [Validation(Required=false)]
                public string TaskAction { get; set; }

            }

        }

        /// <summary>
        /// <para>The request ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>90496720-2319-42A8-87CD-FCE4DF95EBED</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

    }

}
