// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Domain20180129.Models
{
    public class QueryRegistrantProfilesRequest : TeaModel {
        /// <summary>
        /// <para>Specifies whether the profile is the default profile. Valid values:</para>
        /// <list type="bullet">
        /// <item><description><b>true</b>: The default profile.</description></item>
        /// <item><description><b>false</b>: Not the default profile.</description></item>
        /// </list>
        /// <para>Default value: <b>false</b>.</para>
        /// 
        /// <b>Example:</b>
        /// <para>false</para>
        /// </summary>
        [NameInMap("DefaultRegistrantProfile")]
        [Validation(Required=false)]
        public bool? DefaultRegistrantProfile { get; set; }

        /// <summary>
        /// <para>The email address.</para>
        /// 
        /// <b>Example:</b>
        /// <para><a href="mailto:username@example.com">username@example.com</a></para>
        /// </summary>
        [NameInMap("Email")]
        [Validation(Required=false)]
        public string Email { get; set; }

        /// <summary>
        /// <para>The language of the error message returned by the interface. Valid values:</para>
        /// <list type="bullet">
        /// <item><description><b>zh</b>: Chinese.</description></item>
        /// <item><description><b>en</b>: English.</description></item>
        /// </list>
        /// <para>Default value: <b>en</b>.</para>
        /// 
        /// <b>Example:</b>
        /// <para>en</para>
        /// </summary>
        [NameInMap("Lang")]
        [Validation(Required=false)]
        public string Lang { get; set; }

        /// <summary>
        /// <para>The page number. Default value: <b>0</b>.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("PageNum")]
        [Validation(Required=false)]
        public int? PageNum { get; set; }

        /// <summary>
        /// <para>The number of records per page. Default value: <b>0</b>. Maximum value: <b>5000</b>.</para>
        /// 
        /// <b>Example:</b>
        /// <para>500</para>
        /// </summary>
        [NameInMap("PageSize")]
        [Validation(Required=false)]
        public int? PageSize { get; set; }

        /// <summary>
        /// <para>The real-name verification status. Valid values:</para>
        /// <list type="bullet">
        /// <item><description><b>FAILED</b>: Real-name verification failed.</description></item>
        /// <item><description><b>SUCCEED</b>: Real-name verification succeeded.</description></item>
        /// <item><description><b>NONAUDIT</b>: Not verified.</description></item>
        /// <item><description><b>AUDITING</b>: Under review.</description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>SUCCEED</para>
        /// </summary>
        [NameInMap("RealNameStatus")]
        [Validation(Required=false)]
        public string RealNameStatus { get; set; }

        /// <summary>
        /// <para>The name of the domain name registrant (in English).</para>
        /// 
        /// <b>Example:</b>
        /// <para>li si</para>
        /// </summary>
        [NameInMap("RegistrantOrganization")]
        [Validation(Required=false)]
        public string RegistrantOrganization { get; set; }

        /// <summary>
        /// <para>The ID of the registrant profile to query. This ID is automatically generated by the system after the registrant profile is created.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1234567</para>
        /// </summary>
        [NameInMap("RegistrantProfileId")]
        [Validation(Required=false)]
        public long? RegistrantProfileId { get; set; }

        /// <summary>
        /// <para>The template type. Valid values:</para>
        /// <list type="bullet">
        /// <item><description><b>common</b>: Common template.</description></item>
        /// <item><description><b>cnnic</b>: CNNIC template.</description></item>
        /// </list>
        /// <remarks>
        /// <para>The CNNIC template is supported only on the international site. Domain names such as &quot;.cn&quot; and &quot;.中国&quot; registered under the CNNIC registry on the Alibaba Cloud International Website (<a href="http://www.alibabacloud.com">www.alibabacloud.com</a>) must use the CNNIC template. Other domain names use the common template.</para>
        /// </remarks>
        /// 
        /// <b>Example:</b>
        /// <para>common</para>
        /// </summary>
        [NameInMap("RegistrantProfileType")]
        [Validation(Required=false)]
        public string RegistrantProfileType { get; set; }

        /// <summary>
        /// <para>The type of the domain name registrant. Valid values:</para>
        /// <list type="bullet">
        /// <item><description><b>1</b>: Individual.</description></item>
        /// <item><description><b>2</b>: Enterprise.</description></item>
        /// </list>
        /// <para>Default value: <b>1</b>.</para>
        /// 
        /// <b>Example:</b>
        /// <para>1</para>
        /// </summary>
        [NameInMap("RegistrantType")]
        [Validation(Required=false)]
        public string RegistrantType { get; set; }

        /// <summary>
        /// <para>The remarks.</para>
        /// 
        /// <b>Example:</b>
        /// <para>my domain remark</para>
        /// </summary>
        [NameInMap("Remark")]
        [Validation(Required=false)]
        public string Remark { get; set; }

        /// <summary>
        /// <para>The user IP address. You can set this parameter to 127.0.0.1.</para>
        /// 
        /// <b>Example:</b>
        /// <para>127.0.0.1</para>
        /// </summary>
        [NameInMap("UserClientIp")]
        [Validation(Required=false)]
        public string UserClientIp { get; set; }

        /// <summary>
        /// <para>The name of the domain name registrant (in Chinese).</para>
        /// 
        /// <b>Example:</b>
        /// <para>李四</para>
        /// </summary>
        [NameInMap("ZhRegistrantOrganization")]
        [Validation(Required=false)]
        public string ZhRegistrantOrganization { get; set; }

    }

}
