// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Ecd20201002.Models
{
    public class GetConnectionTicketRequest : TeaModel {
        [NameInMap("AccessType")]
        [Validation(Required=false)]
        public string AccessType { get; set; }

        /// <summary>
        /// <para>A unique ID generated by the client.</para>
        /// <para>This parameter is required.</para>
        /// 
        /// <b>Example:</b>
        /// <para>f4a0dc8e-1702-4728-9a60-95b27a35****</para>
        /// </summary>
        [NameInMap("ClientId")]
        [Validation(Required=false)]
        public string ClientId { get; set; }

        /// <summary>
        /// <para>The client operating system.</para>
        /// 
        /// <b>Example:</b>
        /// <para>Windows_NT 10.0.18363 x64</para>
        /// </summary>
        [NameInMap("ClientOS")]
        [Validation(Required=false)]
        public string ClientOS { get; set; }

        /// <summary>
        /// <para>The client type.</para>
        /// 
        /// <b>Example:</b>
        /// <para>windows</para>
        /// </summary>
        [NameInMap("ClientType")]
        [Validation(Required=false)]
        public string ClientType { get; set; }

        /// <summary>
        /// <para>The client version.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2.1.0-R-20210731.151756</para>
        /// </summary>
        [NameInMap("ClientVersion")]
        [Validation(Required=false)]
        public string ClientVersion { get; set; }

        /// <summary>
        /// <para>This parameter lets you configure a custom user-mode application. After a ticket is obtained, the application is automatically run.</para>
        /// <list type="bullet">
        /// <item><description><para>appPath: A string that specifies the path of the application startup file. For example, <c>&quot;C:\\Program Files (x86)\\000\\000.exe&quot;</c>. Note: Use double backslashes (\) as separators.</para>
        /// </description></item>
        /// <item><description><para>appParameter: A string that specifies the startup parameters of the application. For example, <c>&quot;meetingid 000 meetingname aaa&quot;</c>. Note: Use spaces to separate parameters.</para>
        /// </description></item>
        /// </list>
        /// 
        /// <b>Example:</b>
        /// <para>{
        ///       &quot;startApplication&quot;: {
        ///             &quot;startApplicationList&quot;: [
        ///                   {
        ///                         &quot;sessionName&quot;: &quot;&quot;,
        ///                         &quot;appList&quot;: [
        ///                               {
        ///                                     &quot;appPath&quot;: &quot;C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe&quot;,
        ///                                     &quot;appParameter&quot;: &quot;<a href="http://www.example.com">www.example.com</a> <a href="http://www.example1.com">www.example1.com</a>&quot;
        ///                               }
        ///                         ]
        ///                   }
        ///             ]
        ///       }
        /// }</para>
        /// </summary>
        [NameInMap("CommandContent")]
        [Validation(Required=false)]
        public string CommandContent { get; set; }

        /// <summary>
        /// <para>The cloud computer ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>ecd-gx2x1dhsmucyy****</para>
        /// </summary>
        [NameInMap("DesktopId")]
        [Validation(Required=false)]
        public string DesktopId { get; set; }

        /// <summary>
        /// <para>The logon credential. Call GetLoginToken to obtain this credential.</para>
        /// <para>This parameter is required.</para>
        /// 
        /// <b>Example:</b>
        /// <para>v18101ac6a9e69c66b04a163031680463660b4b216cd758f34b60b9ad6a7c7f7334b83dd8f75eef4209c68f9f1080b****</para>
        /// </summary>
        [NameInMap("LoginToken")]
        [Validation(Required=false)]
        public string LoginToken { get; set; }

        [NameInMap("OwnerId")]
        [Validation(Required=false)]
        public long? OwnerId { get; set; }

        /// <summary>
        /// <para>The region ID. Call <a href="t2223508.xdita#"></a>to get a list of regions that Elastic Desktop Service (EDS) supports.</para>
        /// <para>This parameter is required.</para>
        /// 
        /// <b>Example:</b>
        /// <para>cn-hangzhou</para>
        /// </summary>
        [NameInMap("RegionId")]
        [Validation(Required=false)]
        public string RegionId { get; set; }

        [NameInMap("ResourceOwnerAccount")]
        [Validation(Required=false)]
        public string ResourceOwnerAccount { get; set; }

        [NameInMap("ResourceOwnerId")]
        [Validation(Required=false)]
        public long? ResourceOwnerId { get; set; }

        /// <summary>
        /// <para>The session ID. Call GetLoginToken to obtain this ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>cd45e873-650d-4d70-acb9-f996187a****</para>
        /// </summary>
        [NameInMap("SessionId")]
        [Validation(Required=false)]
        public string SessionId { get; set; }

        /// <summary>
        /// <para>A list of tags. You can include 1 to 20 tags.</para>
        /// </summary>
        [NameInMap("Tag")]
        [Validation(Required=false)]
        public List<GetConnectionTicketRequestTag> Tag { get; set; }
        public class GetConnectionTicketRequestTag : TeaModel {
            /// <summary>
            /// <para>The tag key. If you specify <c>Tag</c>, <c>Key</c> is required. The key cannot exceed 128 characters in length. It cannot start with <c>aliyun</c> or <c>acs:</c>, contain <c>http://</c> or <c>https://</c>, or consist of only spaces.</para>
            /// 
            /// <b>Example:</b>
            /// <para>TestKey</para>
            /// </summary>
            [NameInMap("Key")]
            [Validation(Required=false)]
            public string Key { get; set; }

            /// <summary>
            /// <para>The tag value. The value can be an empty string. It can be up to 128 characters in length. It cannot start with <c>acs:</c> or contain <c>http://</c> or <c>https://</c>.</para>
            /// 
            /// <b>Example:</b>
            /// <para>TestValue</para>
            /// </summary>
            [NameInMap("Value")]
            [Validation(Required=false)]
            public string Value { get; set; }

        }

        /// <summary>
        /// <para>The ID of the cloud computer connection task.<br>Do not specify this parameter in your first call. For subsequent calls, set this parameter to the <c>TaskId</c> returned from the previous call.<br></para>
        /// 
        /// <b>Example:</b>
        /// <para>2afbad19-778a-4fc5-9674-1f19c638****</para>
        /// </summary>
        [NameInMap("TaskId")]
        [Validation(Required=false)]
        public string TaskId { get; set; }

        [NameInMap("TicketBlackList")]
        [Validation(Required=false)]
        public List<string> TicketBlackList { get; set; }

        /// <summary>
        /// <para>The unique identifier of the client. If you use a Alibaba Cloud Workspace client, find this parameter in the <b>About</b> dialog box on the logon screen.</para>
        /// 
        /// <b>Example:</b>
        /// <para>28c80e90-f71e-4c23-93d6-1225329cf949</para>
        /// </summary>
        [NameInMap("Uuid")]
        [Validation(Required=false)]
        public string Uuid { get; set; }

    }

}
