// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Ecd20201002.Models
{
    public class GetLoginTokenRequest : TeaModel {
        /// <summary>
        /// The verification code that is generated by the virtual MFA device. This parameter is required if you set `CurrentStage` to `MFAVerify`.
        /// </summary>
        [NameInMap("AuthenticationCode")]
        [Validation(Required=false)]
        public string AuthenticationCode { get; set; }

        /// <summary>
        /// The ID of the Alibaba Cloud Workspace client. The system generates a unique ID for each client.
        /// 
        /// This parameter is required.
        /// </summary>
        [NameInMap("ClientId")]
        [Validation(Required=false)]
        public string ClientId { get; set; }

        /// <summary>
        /// The operating system (OS) of the device that runs an Alibaba Cloud Workspace client.
        /// </summary>
        [NameInMap("ClientOS")]
        [Validation(Required=false)]
        public string ClientOS { get; set; }

        /// <summary>
        /// The type of Alibaba Cloud Workspace clients.
        /// 
        /// Valid values:
        /// 
        /// *   HTML5: web client.
        /// 
        /// *   WINDOWS: Windows client.
        /// 
        /// *   MACOS: macOS client.
        /// 
        /// *   IOS: iOS client.
        /// 
        /// *   ANDROID: Android client.
        /// </summary>
        [NameInMap("ClientType")]
        [Validation(Required=false)]
        public string ClientType { get; set; }

        /// <summary>
        /// The version of the client. When you use an Alibaba Cloud Workspace client, you can view the client version in the **About** dialog box on the client logon page.
        /// </summary>
        [NameInMap("ClientVersion")]
        [Validation(Required=false)]
        public string ClientVersion { get; set; }

        /// <summary>
        /// The logon authentication stage. Valid values:
        /// 
        /// *   `ADPassword`: the stage to verify the identity of the Active Directory (AD) user. You must specify the value when the system verifies the identity of a convenience account or an AD account.
        /// *   `MFABind: the stage to bind a virtual multi-factor authentication (MFA) device.`
        /// *   `MFAVerify: the stage to verify the verification code that is generated by the virtual MFA device.`
        /// *   `TokenVerify`: the stage to perform two-factor authentication on an Alibaba Cloud Workspace client (hereinafter referred to as the client).
        /// *   `ChangePassword`: the stage to change the password of the user.
        /// *   `KeepAliveVerify`: the stage to obtain LoginToken if KeepAliveToken is valid.
        /// </summary>
        [NameInMap("CurrentStage")]
        [Validation(Required=false)]
        public string CurrentStage { get; set; }

        /// <summary>
        /// The office network ID. This parameter has the same meaning as `OfficeSiteId`. We recommend that you replace `DirectoryId` with `OfficeSiteId`. You can specify a value for `DirectoryId` or `OfficeSiteId`.
        /// </summary>
        [NameInMap("DirectoryId")]
        [Validation(Required=false)]
        public string DirectoryId { get; set; }

        /// <summary>
        /// The name of the convenience user or the AD user. This parameter is required if you set `CurrentStage` to `ADPassword`.
        /// </summary>
        [NameInMap("EndUserId")]
        [Validation(Required=false)]
        public string EndUserId { get; set; }

        /// <summary>
        /// Specifies whether to keep the user logged on to the client. 
        /// Valid values:
        /// * null: Default value. Do not keep the user logged on to the client.
        /// * true: Keep the user logged on to the client.
        /// * false:  Do not keep the user logged on to the client.
        /// </summary>
        [NameInMap("KeepAlive")]
        [Validation(Required=false)]
        public bool? KeepAlive { get; set; }

        /// <summary>
        /// The token to keep logging on to an Alibaba Cloud Workspace client. When an end user logs on to the Alibaba Cloud Workspace client and select Auto Sign-in, `KeepAliveToken` is returned after you call this operation. Within the valid period of the returned token``, you can call the `GetLoginToken` operation and set `CurrentStage` to `KeepAliveVerify`. Then, you can obtain LoginToken. If you set `CurrentStage` to `KeepAliveVerify`, `KeepAliveToken` is required.
        /// </summary>
        [NameInMap("KeepAliveToken")]
        [Validation(Required=false)]
        public string KeepAliveToken { get; set; }

        /// <summary>
        /// The new password. This parameter is required if you set `CurrentStage` to `ChangePassword`.
        /// </summary>
        [NameInMap("NewPassword")]
        [Validation(Required=false)]
        public string NewPassword { get; set; }

        /// <summary>
        /// The office network ID.
        /// </summary>
        [NameInMap("OfficeSiteId")]
        [Validation(Required=false)]
        public string OfficeSiteId { get; set; }

        /// <summary>
        /// The current password. This parameter is required if you set `CurrentStage` to `ChangePassword`.
        /// </summary>
        [NameInMap("OldPassword")]
        [Validation(Required=false)]
        public string OldPassword { get; set; }

        /// <summary>
        /// The password of the convenience user or the AD user. This parameter is required if you set `CurrentStage` to `ADPassword`.
        /// </summary>
        [NameInMap("Password")]
        [Validation(Required=false)]
        public string Password { get; set; }

        /// <summary>
        /// The region ID. You can call the [DescribeRegions](https://help.aliyun.com/document_detail/196646.html) operation to query the regions supported by EDS.
        /// 
        /// This parameter is required.
        /// </summary>
        [NameInMap("RegionId")]
        [Validation(Required=false)]
        public string RegionId { get; set; }

        /// <summary>
        /// The ID of the session.
        /// 
        /// *   If the virtual multi-factor authentication (MFA) device is not bound or two-factor authentication is not enabled for the client, you do not need to specify a value for `SessionId`.
        /// *   If the virtual MFA device is not bound or two-factor authentication is enabled for the client, you must specify a value for `SessionId` to verify the user identity after you specify a value for `ADPassword`. The value of the `SessionId` parameter is returned only if the CurrentStage parameter is set to `ADPassword` when you call the `GetLoginToken` operation.
        /// </summary>
        [NameInMap("SessionId")]
        [Validation(Required=false)]
        public string SessionId { get; set; }

        /// <summary>
        /// If two-factor authentication is enabled for Alibaba Cloud Workspace terminals in the EDS console and the system detects that the current logon user is exposed to risks, the system sends a verification code to the email address of the user. This parameter is required if you set `CurrentStage` to `TokenVerify`.
        /// </summary>
        [NameInMap("TokenCode")]
        [Validation(Required=false)]
        public string TokenCode { get; set; }

        /// <summary>
        /// The unique identifier of the client. When you use an Alibaba Cloud Workspace client, you can view the client version in the **About** dialog box on the client logon page.
        /// </summary>
        [NameInMap("Uuid")]
        [Validation(Required=false)]
        public string Uuid { get; set; }

    }

}
