// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Waf_openapi20211001.Models
{
    public class DescribeDefenseRulesResponseBody : TeaModel {
        /// <summary>
        /// <para>The ID of the request.</para>
        /// 
        /// <b>Example:</b>
        /// <para>80736FA5-FA87-55F6-AA69-C5477C6FE6D0</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>An array of protection rules.</para>
        /// </summary>
        [NameInMap("Rules")]
        [Validation(Required=false)]
        public List<DescribeDefenseRulesResponseBodyRules> Rules { get; set; }
        public class DescribeDefenseRulesResponseBodyRules : TeaModel {
            /// <summary>
            /// <para>The details of the protection rule. The value is a string that contains multiple parameters in the JSON format. For more information, see the &quot;<b>Rule parameters</b>&quot; section in the <a href="~~CreateDefenseRule~~">CreateDefenseRule</a> topic.</para>
            /// 
            /// <b>Example:</b>
            /// <para>{\&quot;policyId\&quot;:1012,\&quot;action\&quot;:\&quot;block\&quot;}</para>
            /// </summary>
            [NameInMap("Config")]
            [Validation(Required=false)]
            public string Config { get; set; }

            /// <summary>
            /// <para>The origin of the protection rule. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>custom:</b> The protection rule is created by the user.</description></item>
            /// <item><description><b>system:</b> The protection rule is automatically generated by the system.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>custom</para>
            /// </summary>
            [NameInMap("DefenseOrigin")]
            [Validation(Required=false)]
            public string DefenseOrigin { get; set; }

            /// <summary>
            /// <para>The scenario in which the protection rule is used. For more information, see the description of the <b>DefenseScene</b> parameter in the <a href="~~CreateDefenseRule~~">CreateDefenseRule</a> topic.</para>
            /// 
            /// <b>Example:</b>
            /// <para>waf_group</para>
            /// </summary>
            [NameInMap("DefenseScene")]
            [Validation(Required=false)]
            public string DefenseScene { get; set; }

            /// <summary>
            /// <para>The most recent time when the protection rule was modified.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1665460629000</para>
            /// </summary>
            [NameInMap("GmtModified")]
            [Validation(Required=false)]
            public long? GmtModified { get; set; }

            /// <summary>
            /// <para>The ID of the protection rule.</para>
            /// 
            /// <b>Example:</b>
            /// <para>42755</para>
            /// </summary>
            [NameInMap("RuleId")]
            [Validation(Required=false)]
            public long? RuleId { get; set; }

            /// <summary>
            /// <para>The name of the protection rule.</para>
            /// 
            /// <b>Example:</b>
            /// <para>rules_41</para>
            /// </summary>
            [NameInMap("RuleName")]
            [Validation(Required=false)]
            public string RuleName { get; set; }

            /// <summary>
            /// <para>The status of the protection rule. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>0:</b> disabled.</description></item>
            /// <item><description><b>1:</b> enabled.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("Status")]
            [Validation(Required=false)]
            public int? Status { get; set; }

            /// <summary>
            /// <para>The ID of the protection rule template.</para>
            /// 
            /// <b>Example:</b>
            /// <para>5673</para>
            /// </summary>
            [NameInMap("TemplateId")]
            [Validation(Required=false)]
            public long? TemplateId { get; set; }

        }

        /// <summary>
        /// <para>The total number of returned entries.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2</para>
        /// </summary>
        [NameInMap("TotalCount")]
        [Validation(Required=false)]
        public long? TotalCount { get; set; }

    }

}
