// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Waf_openapi20211001.Models
{
    public class DescribeCloudResourceAccessPortDetailsResponseBody : TeaModel {
        /// <summary>
        /// <para>The port details of cloud service instances connected to WAF.</para>
        /// </summary>
        [NameInMap("AccessPortDetails")]
        [Validation(Required=false)]
        public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetails> AccessPortDetails { get; set; }
        public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetails : TeaModel {
            /// <summary>
            /// <para>The list of certificates for the cloud service ports connected to WAF.</para>
            /// </summary>
            [NameInMap("Certificates")]
            [Validation(Required=false)]
            public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsCertificates> Certificates { get; set; }
            public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsCertificates : TeaModel {
                /// <summary>
                /// <para>The certificate type for the HTTPS protocol. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><para><b>default</b>: default certificate.</para>
                /// </description></item>
                /// <item><description><para><b>extension</b>: extension certificate.</para>
                /// </description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>default</para>
                /// </summary>
                [NameInMap("AppliedType")]
                [Validation(Required=false)]
                public string AppliedType { get; set; }

                /// <summary>
                /// <para>The ID of the added certificate.</para>
                /// 
                /// <b>Example:</b>
                /// <para>123-cn-hangzhou</para>
                /// </summary>
                [NameInMap("CertificateId")]
                [Validation(Required=false)]
                public string CertificateId { get; set; }

                /// <summary>
                /// <para>The certificate name.</para>
                /// 
                /// <b>Example:</b>
                /// <para>cert-name1</para>
                /// </summary>
                [NameInMap("CertificateName")]
                [Validation(Required=false)]
                public string CertificateName { get; set; }

            }

            /// <summary>
            /// <para>The cipher suite type. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>1</b>: all cipher suites are added.</para>
            /// </description></item>
            /// <item><description><para><b>2</b>: strong cipher suites are added. This value is available only when TLSVersion is set to tlsv1.2.</para>
            /// </description></item>
            /// <item><description><para><b>99</b>: custom cipher suites are added. This value is available only when TLSVersion is not set to tlsv1.3.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("CipherSuite")]
            [Validation(Required=false)]
            public int? CipherSuite { get; set; }

            /// <summary>
            /// <para>The ID of the connected resource, automatically generated by WAF.</para>
            /// 
            /// <b>Example:</b>
            /// <para>i-bp1**************7ey-80-ecs</para>
            /// </summary>
            [NameInMap("CloudResourceId")]
            [Validation(Required=false)]
            public string CloudResourceId { get; set; }

            /// <summary>
            /// <para>The specific custom cipher suites to add. This parameter is used only when <b>CipherSuite</b> is set to <b>99</b>.</para>
            /// </summary>
            [NameInMap("CustomCiphers")]
            [Validation(Required=false)]
            public List<string> CustomCiphers { get; set; }

            /// <summary>
            /// <para>Indicates whether TLS 1.3 is supported. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b>: TLS 1.3 is supported.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: TLS 1.3 is not supported.</para>
            /// </description></item>
            /// </list>
            /// <remarks>
            /// <para>This parameter is used only when HttpsPorts is not empty (the domain name uses the HTTPS protocol). When TLSVersion is set to tlsv1.3, this value must be true.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("EnableTLSv3")]
            [Validation(Required=false)]
            public bool? EnableTLSv3 { get; set; }

            /// <summary>
            /// <para>Indicates whether HTTP/2 is enabled. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b>: HTTP/2 is enabled.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: HTTP/2 is disabled.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>True</para>
            /// </summary>
            [NameInMap("Http2Enabled")]
            [Validation(Required=false)]
            public bool? Http2Enabled { get; set; }

            /// <summary>
            /// <para>Indicates whether keep-alive connections are enabled. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b> (default): Keep-alive connections are enabled.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: Keep-alive connections are disabled.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("Keepalive")]
            [Validation(Required=false)]
            public bool? Keepalive { get; set; }

            /// <summary>
            /// <para>The number of requests that can reuse a keep-alive connection. Valid values: 60 to 1000.</para>
            /// <remarks>
            /// <para>Specifies how many requests can reuse a keep-alive connection after keep-alive is enabled.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>1000</para>
            /// </summary>
            [NameInMap("KeepaliveRequests")]
            [Validation(Required=false)]
            public int? KeepaliveRequests { get; set; }

            /// <summary>
            /// <para>The idle timeout period for keep-alive connections. Valid values: 10 to 3600. Default value: 15. Unit: seconds.</para>
            /// <remarks>
            /// <para>Specifies how long an idle keep-alive connection is retained before it is released.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>10</para>
            /// </summary>
            [NameInMap("KeepaliveTimeout")]
            [Validation(Required=false)]
            public int? KeepaliveTimeout { get; set; }

            /// <summary>
            /// <para>The traffic tag fields and values of the domain name, used to mark traffic processed by WAF.</para>
            /// <remarks>
            /// <para>This parameter is returned only when the traffic tag feature is enabled for the domain name.</para>
            /// </remarks>
            /// </summary>
            [NameInMap("LogHeaders")]
            [Validation(Required=false)]
            public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsLogHeaders> LogHeaders { get; set; }
            public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsLogHeaders : TeaModel {
                /// <summary>
                /// <para>The specified custom request header field.</para>
                /// 
                /// <b>Example:</b>
                /// <para>key1</para>
                /// </summary>
                [NameInMap("Key")]
                [Validation(Required=false)]
                public string Key { get; set; }

                /// <summary>
                /// <para>The value of the specified custom request header field.</para>
                /// 
                /// <b>Example:</b>
                /// <para>value1</para>
                /// </summary>
                [NameInMap("Value")]
                [Validation(Required=false)]
                public string Value { get; set; }

            }

            /// <summary>
            /// <para>The maximum request body size. Valid values: 2 to 10. Default value: 2. Unit: GB.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("MaxBodySize")]
            [Validation(Required=false)]
            public int? MaxBodySize { get; set; }

            /// <summary>
            /// <para>The UID that indicates the resource ownership of the cloud service.</para>
            /// 
            /// <b>Example:</b>
            /// <para>123</para>
            /// </summary>
            [NameInMap("OwnerUserId")]
            [Validation(Required=false)]
            public string OwnerUserId { get; set; }

            /// <summary>
            /// <para>The port of the cloud service that is connected to WAF.</para>
            /// 
            /// <b>Example:</b>
            /// <para>443</para>
            /// </summary>
            [NameInMap("Port")]
            [Validation(Required=false)]
            public int? Port { get; set; }

            /// <summary>
            /// <para>The protocol type. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><b>http</b>: HTTP protocol.</description></item>
            /// <item><description><b>https</b>: HTTPS protocol.</description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>https</para>
            /// </summary>
            [NameInMap("Protocol")]
            [Validation(Required=false)]
            public string Protocol { get; set; }

            /// <summary>
            /// <para>The read timeout period. Unit: seconds.
            /// Valid values: 1 to 3600.</para>
            /// 
            /// <b>Example:</b>
            /// <para>5</para>
            /// </summary>
            [NameInMap("ReadTimeout")]
            [Validation(Required=false)]
            public int? ReadTimeout { get; set; }

            /// <summary>
            /// <para>The domain name status. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>1</b>: The port is in a normal state.</para>
            /// </description></item>
            /// <item><description><para><b>2</b>: The port is being created.</para>
            /// </description></item>
            /// <item><description><para><b>3</b>: The port is being modified.</para>
            /// </description></item>
            /// <item><description><para><b>4</b>: The port is being released.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("Status")]
            [Validation(Required=false)]
            public int? Status { get; set; }

            /// <summary>
            /// <para>The protection exception status. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>InvalidCert</b>: invalid certificate.</para>
            /// </description></item>
            /// <item><description><para><b>ClientCertOpend</b>: mutual authentication is enabled.</para>
            /// </description></item>
            /// <item><description><para><b>NetworkConfigLost</b>: the cloud service network configuration is abnormal.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>InvalidCert</para>
            /// </summary>
            [NameInMap("SubStatus")]
            [Validation(Required=false)]
            public string SubStatus { get; set; }

            /// <summary>
            /// <para>The specific reasons for the protection exception status. This parameter has a value only when SubStatus is set to InvalidCert.</para>
            /// </summary>
            [NameInMap("SubStatusDetails")]
            [Validation(Required=false)]
            public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsSubStatusDetails> SubStatusDetails { get; set; }
            public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsSubStatusDetails : TeaModel {
                /// <summary>
                /// <para>The certificate type for the HTTPS protocol. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><para><b>default</b>: default certificate.</para>
                /// </description></item>
                /// <item><description><para><b>extension</b>: extension certificate.</para>
                /// </description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>default</para>
                /// </summary>
                [NameInMap("AppliedType")]
                [Validation(Required=false)]
                public string AppliedType { get; set; }

                /// <summary>
                /// <para>The certificate ID in SSL Certificates Service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>123-cn-hangzhou</para>
                /// </summary>
                [NameInMap("CertId")]
                [Validation(Required=false)]
                public string CertId { get; set; }

                /// <summary>
                /// <para>The certificate name in SSL Certificates Service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>test-name</para>
                /// </summary>
                [NameInMap("CertName")]
                [Validation(Required=false)]
                public string CertName { get; set; }

                /// <summary>
                /// <para>The common name (CN).</para>
                /// 
                /// <b>Example:</b>
                /// <para>test.aliyun.com</para>
                /// </summary>
                [NameInMap("CommonName")]
                [Validation(Required=false)]
                public string CommonName { get; set; }

                /// <summary>
                /// <para>The domain name bound to the certificate.</para>
                /// 
                /// <b>Example:</b>
                /// <para>test.aliyun.com</para>
                /// </summary>
                [NameInMap("Domain")]
                [Validation(Required=false)]
                public string Domain { get; set; }

                /// <summary>
                /// <para>The expiration time of the certificate, in UNIX timestamp format. Unit: seconds.</para>
                /// 
                /// <b>Example:</b>
                /// <para>1746328456000</para>
                /// </summary>
                [NameInMap("ExpireTime")]
                [Validation(Required=false)]
                public long? ExpireTime { get; set; }

                /// <summary>
                /// <para>The certificate ID stored in the cloud service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>123</para>
                /// </summary>
                [NameInMap("ProductCertId")]
                [Validation(Required=false)]
                public string ProductCertId { get; set; }

                /// <summary>
                /// <para>The certificate name stored in the cloud service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>test-name</para>
                /// </summary>
                [NameInMap("ProductCertName")]
                [Validation(Required=false)]
                public string ProductCertName { get; set; }

                /// <summary>
                /// <para>The specific reason for the protection exception status. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><para><b>UserUploadCert</b>: The certificate is manually uploaded.</para>
                /// </description></item>
                /// <item><description><para><b>CertNotExistInCertCenter</b>: The certificate does not exist in SSL Certificates Service.</para>
                /// </description></item>
                /// <item><description><para><b>CertExpired</b>: The cloud certificate has expired.</para>
                /// </description></item>
                /// <item><description><para><b>EmptyCertCN</b>: The CN of the certificate is empty.</para>
                /// </description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>CertNotExistInCertCenter</para>
                /// </summary>
                [NameInMap("ReasonCode")]
                [Validation(Required=false)]
                public string ReasonCode { get; set; }

            }

            /// <summary>
            /// <para>The TLS version. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>tlsv1</b>: Supports TLS 1.0 and later. Highest compatibility, lower security.</para>
            /// </description></item>
            /// <item><description><para><b>tlsv1.1</b>: Supports TLS 1.1 and later. Good compatibility, good security.</para>
            /// </description></item>
            /// <item><description><para><b>tlsv1.2</b>: Supports TLS 1.2 and later. Good compatibility, highest security.</para>
            /// </description></item>
            /// <item><description><para><b>tlsv1.3</b>: Supports only TLS 1.3. Highest security, lower compatibility.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>tlsv1</para>
            /// </summary>
            [NameInMap("TLSVersion")]
            [Validation(Required=false)]
            public string TLSVersion { get; set; }

            /// <summary>
            /// <para>The write timeout period. Unit: seconds.
            /// Valid values: 1 to 3600.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("WriteTimeout")]
            [Validation(Required=false)]
            public int? WriteTimeout { get; set; }

            /// <summary>
            /// <para>The method that WAF uses to obtain the originating IP address of the client. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>0</b>: The client traffic does not pass through any Layer 7 proxy before reaching WAF.</para>
            /// </description></item>
            /// <item><description><para><b>1</b>: WAF reads the first value in the X-Forwarded-For (XFF) header as the client IP address.</para>
            /// </description></item>
            /// <item><description><para><b>2</b>: WAF reads the value of a custom header field that you specify as the client IP address.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>0</para>
            /// </summary>
            [NameInMap("XffHeaderMode")]
            [Validation(Required=false)]
            public int? XffHeaderMode { get; set; }

            /// <summary>
            /// <para>The list of custom header fields used to obtain the client IP address, in the format <b>[&quot;header1&quot;,&quot;header2&quot;,...]</b>.</para>
            /// <remarks>
            /// <para>This parameter is required only when <b>XffHeaderMode</b> is set to 2 (WAF reads the value of a custom header field that you specify as the client IP address).</para>
            /// </remarks>
            /// </summary>
            [NameInMap("XffHeaders")]
            [Validation(Required=false)]
            public List<string> XffHeaders { get; set; }

            /// <summary>
            /// <para>Specifies whether the X-Forward-For-Proto header is used to pass the WAF protocol. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b> (default): The WAF protocol is passed.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: The WAF protocol is not passed.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("XffProto")]
            [Validation(Required=false)]
            public bool? XffProto { get; set; }

        }

        /// <summary>
        /// <para>The request ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2EFCFE18-78F8-5079-B312-07***48B</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>The total number of entries returned.</para>
        /// 
        /// <b>Example:</b>
        /// <para>10</para>
        /// </summary>
        [NameInMap("TotalCount")]
        [Validation(Required=false)]
        public int? TotalCount { get; set; }

    }

}
