// This file is auto-generated, don't edit it. Thanks.

using System;
using System.Collections.Generic;
using System.IO;

using Tea;

namespace AlibabaCloud.SDK.Waf_openapi20211001.Models
{
    public class DescribeCloudResourceAccessPortDetailsResponseBody : TeaModel {
        /// <summary>
        /// <para>The details of the ports for the cloud service instance that is added to WAF.</para>
        /// </summary>
        [NameInMap("AccessPortDetails")]
        [Validation(Required=false)]
        public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetails> AccessPortDetails { get; set; }
        public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetails : TeaModel {
            /// <summary>
            /// <para>The list of certificates for the port of the cloud service instance.</para>
            /// </summary>
            [NameInMap("Certificates")]
            [Validation(Required=false)]
            public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsCertificates> Certificates { get; set; }
            public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsCertificates : TeaModel {
                /// <summary>
                /// <para>The type of the certificate for the HTTPS protocol. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><para><b>default</b>: the default certificate.</para>
                /// </description></item>
                /// <item><description><para><b>extension</b>: the additional certificate.</para>
                /// </description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>default</para>
                /// </summary>
                [NameInMap("AppliedType")]
                [Validation(Required=false)]
                public string AppliedType { get; set; }

                /// <summary>
                /// <para>The ID of the added certificate.</para>
                /// 
                /// <b>Example:</b>
                /// <para>123-cn-hangzhou</para>
                /// </summary>
                [NameInMap("CertificateId")]
                [Validation(Required=false)]
                public string CertificateId { get; set; }

                /// <summary>
                /// <para>The name of the certificate.</para>
                /// 
                /// <b>Example:</b>
                /// <para>cert-name1</para>
                /// </summary>
                [NameInMap("CertificateName")]
                [Validation(Required=false)]
                public string CertificateName { get; set; }

            }

            /// <summary>
            /// <para>The type of the cipher suite. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>1</b>: all cipher suites.</para>
            /// </description></item>
            /// <item><description><para><b>2</b>: strong cipher suites.</para>
            /// </description></item>
            /// <item><description><para><b>99</b>: custom cipher suites.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("CipherSuite")]
            [Validation(Required=false)]
            public int? CipherSuite { get; set; }

            /// <summary>
            /// <para>The ID of the resource that is added to WAF. The ID is automatically generated by WAF.</para>
            /// 
            /// <b>Example:</b>
            /// <para>i-bp1**************7ey-80-ecs</para>
            /// </summary>
            [NameInMap("CloudResourceId")]
            [Validation(Required=false)]
            public string CloudResourceId { get; set; }

            /// <summary>
            /// <para>The custom cipher suites. This parameter is returned only when <b>CipherSuite</b> is set to <b>99</b>.</para>
            /// </summary>
            [NameInMap("CustomCiphers")]
            [Validation(Required=false)]
            public List<string> CustomCiphers { get; set; }

            /// <summary>
            /// <para>Indicates whether TLS 1.3 is supported. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b>: TLS 1.3 is supported.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: TLS 1.3 is not supported.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("EnableTLSv3")]
            [Validation(Required=false)]
            public bool? EnableTLSv3 { get; set; }

            /// <summary>
            /// <para>Indicates whether HTTP/2 is enabled. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b>: HTTP/2 is enabled.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: HTTP/2 is not enabled.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>True</para>
            /// </summary>
            [NameInMap("Http2Enabled")]
            [Validation(Required=false)]
            public bool? Http2Enabled { get; set; }

            /// <summary>
            /// <para>Indicates whether to enable persistent connections. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b>: Enables persistent connections. This is the default value.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: Disables persistent connections.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("Keepalive")]
            [Validation(Required=false)]
            public bool? Keepalive { get; set; }

            /// <summary>
            /// <para>The number of requests that can be reused in a persistent connection. Valid values: 60 to 1000.</para>
            /// <remarks>
            /// <para>This parameter specifies the number of requests that can be reused after a persistent connection is established.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>1000</para>
            /// </summary>
            [NameInMap("KeepaliveRequests")]
            [Validation(Required=false)]
            public int? KeepaliveRequests { get; set; }

            /// <summary>
            /// <para>The timeout period for an idle persistent connection. Valid values: 10 to 3600. Default value: 15. Unit: seconds.</para>
            /// <remarks>
            /// <para>This parameter specifies the period of time after which an idle persistent connection is released.</para>
            /// </remarks>
            /// 
            /// <b>Example:</b>
            /// <para>10</para>
            /// </summary>
            [NameInMap("KeepaliveTimeout")]
            [Validation(Required=false)]
            public int? KeepaliveTimeout { get; set; }

            /// <summary>
            /// <para>The key-value pair that is used to tag the traffic that is processed by WAF.</para>
            /// <remarks>
            /// <para>This parameter is returned only when the traffic tagging feature is enabled for the domain name.</para>
            /// </remarks>
            /// </summary>
            [NameInMap("LogHeaders")]
            [Validation(Required=false)]
            public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsLogHeaders> LogHeaders { get; set; }
            public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsLogHeaders : TeaModel {
                /// <summary>
                /// <para>The custom request header field.</para>
                /// 
                /// <b>Example:</b>
                /// <para>key1</para>
                /// </summary>
                [NameInMap("Key")]
                [Validation(Required=false)]
                public string Key { get; set; }

                /// <summary>
                /// <para>The value of the custom request header field.</para>
                /// 
                /// <b>Example:</b>
                /// <para>value1</para>
                /// </summary>
                [NameInMap("Value")]
                [Validation(Required=false)]
                public string Value { get; set; }

            }

            /// <summary>
            /// <para>The maximum size of a request body. Valid values: 2 to 10. Default value: 2. Unit: GB.</para>
            /// 
            /// <b>Example:</b>
            /// <para>2</para>
            /// </summary>
            [NameInMap("MaxBodySize")]
            [Validation(Required=false)]
            public int? MaxBodySize { get; set; }

            /// <summary>
            /// <para>The ID of the Alibaba Cloud account to which the cloud service belongs.</para>
            /// 
            /// <b>Example:</b>
            /// <para>123</para>
            /// </summary>
            [NameInMap("OwnerUserId")]
            [Validation(Required=false)]
            public string OwnerUserId { get; set; }

            /// <summary>
            /// <para>The port of the cloud service that is added to WAF.</para>
            /// 
            /// <b>Example:</b>
            /// <para>443</para>
            /// </summary>
            [NameInMap("Port")]
            [Validation(Required=false)]
            public int? Port { get; set; }

            /// <summary>
            /// <para>The protocol. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>http</b>: HTTP.</para>
            /// </description></item>
            /// <item><description><para><b>https</b>: HTTPS.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>https</para>
            /// </summary>
            [NameInMap("Protocol")]
            [Validation(Required=false)]
            public string Protocol { get; set; }

            /// <summary>
            /// <para>The read timeout period. Unit: seconds. Valid values: 1 to 3600.</para>
            /// 
            /// <b>Example:</b>
            /// <para>5</para>
            /// </summary>
            [NameInMap("ReadTimeout")]
            [Validation(Required=false)]
            public int? ReadTimeout { get; set; }

            /// <summary>
            /// <para>The status of the domain name. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>1</b>: The port is in the Normal state.</para>
            /// </description></item>
            /// <item><description><para><b>2</b>: The port is being created.</para>
            /// </description></item>
            /// <item><description><para><b>3</b>: The port is being modified.</para>
            /// </description></item>
            /// <item><description><para><b>4</b>: The port is being released.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("Status")]
            [Validation(Required=false)]
            public int? Status { get; set; }

            /// <summary>
            /// <para>The abnormal protection status. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>InvalidCert</b>: The certificate is invalid.</para>
            /// </description></item>
            /// <item><description><para><b>ClientCertOpend</b>: Mutual authentication is enabled.</para>
            /// </description></item>
            /// <item><description><para><b>NetworkConfigLost</b>: The network configuration of the cloud service is abnormal.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>InvalidCert</para>
            /// </summary>
            [NameInMap("SubStatus")]
            [Validation(Required=false)]
            public string SubStatus { get; set; }

            /// <summary>
            /// <para>The details of the abnormal protection status. This parameter is returned only when <b>SubStatus</b> is set to InvalidCert.</para>
            /// </summary>
            [NameInMap("SubStatusDetails")]
            [Validation(Required=false)]
            public List<DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsSubStatusDetails> SubStatusDetails { get; set; }
            public class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsSubStatusDetails : TeaModel {
                /// <summary>
                /// <para>The type of the certificate for the HTTPS protocol. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><para><b>default</b>: the default certificate.</para>
                /// </description></item>
                /// <item><description><para><b>extension</b>: the additional certificate.</para>
                /// </description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>default</para>
                /// </summary>
                [NameInMap("AppliedType")]
                [Validation(Required=false)]
                public string AppliedType { get; set; }

                /// <summary>
                /// <para>The ID of the certificate in Certificates Management Service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>123-cn-hangzhou</para>
                /// </summary>
                [NameInMap("CertId")]
                [Validation(Required=false)]
                public string CertId { get; set; }

                /// <summary>
                /// <para>The name of the certificate in Certificates Management Service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>test-name</para>
                /// </summary>
                [NameInMap("CertName")]
                [Validation(Required=false)]
                public string CertName { get; set; }

                /// <summary>
                /// <para>The common name (CN).</para>
                /// 
                /// <b>Example:</b>
                /// <para>test.aliyun.com</para>
                /// </summary>
                [NameInMap("CommonName")]
                [Validation(Required=false)]
                public string CommonName { get; set; }

                /// <summary>
                /// <para>The domain name that is bound to the certificate.</para>
                /// 
                /// <b>Example:</b>
                /// <para>test.aliyun.com</para>
                /// </summary>
                [NameInMap("Domain")]
                [Validation(Required=false)]
                public string Domain { get; set; }

                /// <summary>
                /// <para>The expiration time of the certificate. The value is a UNIX timestamp. Unit: seconds.</para>
                /// 
                /// <b>Example:</b>
                /// <para>1746328456000</para>
                /// </summary>
                [NameInMap("ExpireTime")]
                [Validation(Required=false)]
                public long? ExpireTime { get; set; }

                /// <summary>
                /// <para>The ID of the certificate that is saved for the cloud service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>123</para>
                /// </summary>
                [NameInMap("ProductCertId")]
                [Validation(Required=false)]
                public string ProductCertId { get; set; }

                /// <summary>
                /// <para>The name of the certificate that is saved for the cloud service.</para>
                /// 
                /// <b>Example:</b>
                /// <para>test-name</para>
                /// </summary>
                [NameInMap("ProductCertName")]
                [Validation(Required=false)]
                public string ProductCertName { get; set; }

                /// <summary>
                /// <para>The reason for the abnormal protection status. Valid values:</para>
                /// <list type="bullet">
                /// <item><description><para><b>UserUploadCert</b>: The certificate is manually uploaded.</para>
                /// </description></item>
                /// <item><description><para><b>CertNotExistInCertCenter</b>: The certificate does not exist in Certificates Management Service.</para>
                /// </description></item>
                /// <item><description><para><b>CertExpired</b>: The certificate has expired.</para>
                /// </description></item>
                /// <item><description><para><b>EmptyCertCN</b>: The CN of the certificate is empty.</para>
                /// </description></item>
                /// </list>
                /// 
                /// <b>Example:</b>
                /// <para>CertNotExistInCertCenter</para>
                /// </summary>
                [NameInMap("ReasonCode")]
                [Validation(Required=false)]
                public string ReasonCode { get; set; }

            }

            /// <summary>
            /// <para>The version of the Transport Layer Security (TLS) protocol. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>tlsv1</b></para>
            /// </description></item>
            /// <item><description><para><b>tlsv1.1</b></para>
            /// </description></item>
            /// <item><description><para><b>tlsv1.2</b></para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>tlsv1</para>
            /// </summary>
            [NameInMap("TLSVersion")]
            [Validation(Required=false)]
            public string TLSVersion { get; set; }

            /// <summary>
            /// <para>The write timeout period. Unit: seconds. Valid values: 1 to 3600.</para>
            /// 
            /// <b>Example:</b>
            /// <para>1</para>
            /// </summary>
            [NameInMap("WriteTimeout")]
            [Validation(Required=false)]
            public int? WriteTimeout { get; set; }

            /// <summary>
            /// <para>The mode that WAF uses to obtain the real IP address of a client. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>0</b>: WAF is the first Layer 7 proxy before client traffic is forwarded to the origin server.</para>
            /// </description></item>
            /// <item><description><para><b>1</b>: WAF reads the first IP address from the X-Forwarded-For (XFF) header as the client IP address.</para>
            /// </description></item>
            /// <item><description><para><b>2</b>: WAF reads the value of a custom header as the client IP address.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>0</para>
            /// </summary>
            [NameInMap("XffHeaderMode")]
            [Validation(Required=false)]
            public int? XffHeaderMode { get; set; }

            /// <summary>
            /// <para>The custom header fields that are used to obtain the client IP address. The value is a string in the <c>[&quot;header1&quot;,&quot;header2&quot;,...]</c> format.</para>
            /// <remarks>
            /// <para>This parameter is returned only when <b>XffHeaderMode</b> is set to 2.</para>
            /// </remarks>
            /// </summary>
            [NameInMap("XffHeaders")]
            [Validation(Required=false)]
            public List<string> XffHeaders { get; set; }

            /// <summary>
            /// <para>Indicates whether to use the X-Forwarded-For-Proto header to identify the protocol used by WAF. Valid values:</para>
            /// <list type="bullet">
            /// <item><description><para><b>true</b>: Identifies the protocol used by WAF. This is the default value.</para>
            /// </description></item>
            /// <item><description><para><b>false</b>: Does not identify the protocol used by WAF.</para>
            /// </description></item>
            /// </list>
            /// 
            /// <b>Example:</b>
            /// <para>true</para>
            /// </summary>
            [NameInMap("XffProto")]
            [Validation(Required=false)]
            public bool? XffProto { get; set; }

        }

        /// <summary>
        /// <para>The request ID.</para>
        /// 
        /// <b>Example:</b>
        /// <para>2EFCFE18-78F8-5079-B312-07***48B</para>
        /// </summary>
        [NameInMap("RequestId")]
        [Validation(Required=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// <para>The total number of entries returned.</para>
        /// 
        /// <b>Example:</b>
        /// <para>10</para>
        /// </summary>
        [NameInMap("TotalCount")]
        [Validation(Required=false)]
        public int? TotalCount { get; set; }

    }

}
